### ISSUE TITLE
Documentation updates/improvements

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#100]
- [x]   if Klarna Checkout is not the first payment method in the list, WooCommerce will still be the default checkout;  it should be documented that it is recommended that KCO be the first payment method in the list (if multiple payment methods are active)

- [x] please document that Klarna and Krokedil do not support themes; if functionality tests successfully with the 'Storefront' theme (which is a reasonable, baseline theme), then the issue is up to the theme developer to debug and likely also to resolve.

**Comment by NiklasHogefjord** [comment]
Documentation updated now. I also added a integration flow chart here: https://docs.woocommerce.com/document/klarna-checkout-integration-flow-chart/
