### ISSUE TITLE
KCO several issues: fallback due to an error + no confirmation mail + wrong order numbers

### ISSUE THREAD

**Issue by arashbe** [krokedil/klarna-checkout-for-woocommerce#101]
Hi there,

we are using the KCO Plugin since a few days and have the same problems in LIVE as well as in test mode. Short info about us, which might be helpful:

German Shop using:
- Flatsome Theme
- Germanized Pro Plugin
- PayPal & Stripe gateway
- Sequential Order Numbers Pro

We now have the following problems:

1) On the one hand we as admin do not receive an order confirmation by e-mail if KCO is used. With all other payment options it works without problems. In test mode, however, as a customer we receive an e-mail.

2) Furthermore new orders get arbitrary order numbers, which differ from the "normal" order numbers. See: https://prnt.sc/l36a0x

3) With all orders a KCO error message is to be seen in the order overview in the backend. It reads as follows: "This order was made as a fallback due to an error in the checkout (Error message: Please accept our Terms and Conditions, Revocation Policy and Privacy Policy.). Please verify the order with Klarna." -- See: https://prnt.sc/l36atc

The orders are to be seen however properly in the Klarna backend.

However, these errors are not listed or logged in the Woocommerce system status. See: https://prnt.sc/l36b4o

Need your support.
Thanks in advance

**Comment by NiklasHogefjord** [comment]
Hi,

This error comes from that the Germanized Pro plugin adds extra (or renames the current) terms and conditions checkboxes in the WooCommerce checkout form.

When using Klarna Checkout this checkbox is not being checked (or displayed) in the checkout. This leads to the WooCommerce checkout form not being posted correctly and the order in Woo is created in a fallback sequence.

We have plans to improve compatibility with Germanized plugins but there are several plugins available and a lot of settings/changes that we need to address. 

I'm closing this issue since thre is an open issue for this here: https://github.com/krokedil/klarna-checkout-for-woocommerce/issues/73.

**Comment by arashbe** [comment]
Hi there,
Does this incompatibility cause only the above error number 3 or all the above points?

**Comment by NiklasHogefjord** [comment]
Hi,
The error probably causes all three issues. Try to deactivate the Germanized plugin and make a new purchase. If 1 & 2 persist pleas send a support ticket to support@krokedil.com.

**Comment by arashbe** [comment]
Hi!
I've tried it. The plugin does not cause the other problems.

 

Von: Niklas Högefjord <notifications@github.com> 
Gesendet: Montag, 8. Oktober 2018 12:59
An: krokedil/klarna-checkout-for-woocommerce <klarna-checkout-for-woocommerce@noreply.github.com>
Cc: arashbe <arash00@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [krokedil/klarna-checkout-for-woocommerce] KCO several issues: fallback due to an error + no confirmation mail + wrong order numbers (#101)

 

Hi,
The error probably causes all three issues. Try to deactivate the Germanized plugin and make a new purchase. If 1 & 2 persist pleas send a support ticket to support@krokedil.com <mailto:support@krokedil.com> .

**Comment by SagaraZD** [comment]
Hi  there,
I'm facing to the exact same issue which @arashbe had. But i'm not using this Germanized Pro Plugin for the moment. Any chanse to solve this problem.
