### ISSUE TITLE
Test subscription purchase

### ISSUE THREAD

**Issue by NiklasHogefjord** [krokedil/klarna-checkout-for-woocommerce#105]
Make a purchase with the email address from an existing customer but not logged in.

**Comment by kristibarbosky** [comment]
@NiklasHogefjord - did you recurring test order have shipping (that also should have VAT on the shipping).  I'm getting an error:
"body" : {
      "order_amount" : 2200,
      "order_lines" : [ {
        "name" : "another subscription product",
        "quantity" : 1,
        "total_amount" : 1500,
        "unit_price" : 1500,
        "total_tax_amount" : 250,
        "tax_rate" : 2000
      }, {
        "name" : "Flat rate",
        "quantity" : 1,
        "total_amount" : 700,
        "unit_price" : 700,
        "total_tax_amount" : 0,
        "tax_rate" : 2000
      } ],
      "purchase_currency" : "EUR",
      "order_tax_amount" : 250
    }
  },
  "response" : {
    "timestamp" : "2018-10-10T16:26:01Z",
    "status" : 400,
    "headers" : {
      "Render-Time" : "64",
      "Klarna-Correlation-Id" : "ea972dfb-0b0a-4215-926b-d3def5f86875",
      "Content-Type" : "application/json"
    },
    "body" : {
      "error_code" : "BAD_REQUEST",
      "error_messages" : [ "Bad value: order_lines[1].total_tax_amount" ],
      "correlation_id" : "ea972dfb-0b0a-4215-926b-d3def5f86875"

**Comment by NiklasHogefjord** [comment]
@kristibarbosky, we're going through and documenting our test purchases a bit better now. We will test the following (and will tick them when tested):

- [ ] Purchase with subscription - no start fee, no free trial
- [ ] Purchase with subscription - start fee, no trial
- [ ] Purchase with subscription - no start fee, free trial
- [ ] Purchase with subscription that include shipping
- [ ] Purchase with subscription that contains regular discount
- [ ] Purchase with subscription that contains recurring discount
- [ ] Purchase with subscription that have two different tax classes (shipping one, subscription another)
- [ ] Purchase with two subscriptions in chart
- [ ] Renewal payment with regular subscription
- [ ] Renewal payment with subscription that have shipping
- [ ] Renewal payment with subscription that have recurring discount
- [ ] Place regular subscription + create renewal for all available countries

**Comment by MichaelBengtsson** [comment]
@kristibarbosky I have tested the plugin according to the checks above and i did find a few issues that we need to look at.

However, i can get a recurring payment through with shippment that is taxed. Maybe we can look at this during our meeting today? Maybe there is a setting that you have that i am missing.

**Comment by kristibarbosky** [comment]
1st order:  {
       "type" : "shipping_fee",
       "reference" : "flat_rate:18",
       "name" : "Flat rate",
       "quantity" : 1,
       "unit_price" : 700,
       *"tax_rate" : 0,*
       "total_amount" : 700,
       "total_tax_amount" : 0
     }
2nd (recurring) order:
{
       "name" : "Flat rate",
       "quantity" : 1,
       "total_amount" : 700,
       "unit_price" : 700,
       "total_tax_amount" : 0,
       *"tax_rate" : 2000*
     } ],
both orders & order lines should match & have order_line.type & reference on the 2nd order also

michael [11:07 AM]
yes i can add that in as well.  
https://github.com/krokedil/klarna-checkout-for-woocommerce/blob/master/includes/class-klarna-checkout-for-woocommerce-order-lines-from-order.php#L37
We need to check there if total tax is 0 then rate should be 0
and not run the function

**Comment by MichaelBengtsson** [comment]
Yes this ticket can be closed. Sorry i missed to tag the issue in the commit.
