### ISSUE TITLE
Selecting shipping method does not update the klarna checkout window

### ISSUE THREAD

**Issue by forsvunnet** [krokedil/klarna-checkout-for-woocommerce#106]
Tested with a new WooCommerce installation with just the storefront theme, and the Klarna plugins.

**Steps to reproduce:**

1. Create two flat rate shipping options with the price 50 and 150.
2. Add any product that requires shipping to cart.
3. Go to the checkout page.
4. Observe that the first flat which cost 50 is selected.
5. Select the other costing 150,-
6. Before the Klarna iframe has loaded, select the first shipping option again.

**Expected behaviour:**
When a shipping option is selected the Klarna iframe and Klarna order should be updated.

**Actual behaviour:**
If the Klarna iframe is loading and you select another option, the Klarna order is not updated with the new selection, but the WooCommerce order is.

![screen shot 2018-10-10 at 11 21 11](https://user-images.githubusercontent.com/799281/46726578-f6997d80-cc7e-11e8-8909-2742768f436f.png)

**Comment by incoog** [comment]
I still see this, when I change the shipping method in the shopping cart, the change is not sent to Klarna, so when i go to checkout the previous shipping method is still selected.

**Comment by NiklasHogefjord** [comment]
@incoog This is most likely not a general issue. Get in touch with our support at support@krokedil.com for more information/troubleshooting.
