### ISSUE TITLE
Some KCO orders created on push when using Aelia Foundation Classes for WooCommerce  (PI-512 )

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#109]
A merchant reported 38% (10 of 26) orders were created via push fallback.  They said deactivating the "Aelia Foundation Classes for WooCommerce" plugin resolved the problem.  Further testing would be good (per our call).

![image](https://user-images.githubusercontent.com/15654455/46866135-2a46e580-cdee-11e8-9ad6-1a8e3a9c207b.png)

**Comment by MichaelBengtsson** [comment]
Closed due to lack of information
