### ISSUE TITLE
Handling of EU accounts that don't have EU country as store base country

### ISSUE THREAD

**Issue by NiklasHogefjord** [krokedil/klarna-checkout-for-woocommerce#110]
We've had 2 support tickets now where Swedish merchants have signed up for a KCO v3 EU account but have their Woo store base country set to USA.

Should we add an admin notice saying that this combination doesn't work or should we create some kind of support for this?

**Comment by kristibarbosky** [comment]
Thanks @NiklasHogefjord -  I will escalate this within Klarna to discuss support for these kinds of cases, but I agree that an admin notice would be helpful in this scenario.

**Comment by muntjaber** [comment]
I am closing this since we don't have any current plans for adding this soon.
