### ISSUE TITLE
Google campaign urls (UTM) not registering sales with Klarna plugin

### ISSUE THREAD

**Issue by orjansteffensen** [krokedil/klarna-checkout-for-woocommerce#115]
Just discovered that purchases with UTM-codes are not registered. Users/sessions are registered, but not transactions. Worked fine before changing to Klarna.

**Comment by NiklasHogefjord** [comment]
@boozebrorsan & @MichaelBengtsson perhaps you can collaborate regarding this issue?

**Comment by orjansteffensen** [comment]
I did a test with utm now, and the purchase was successfully registered in Analytics with utm-code.
