### ISSUE TITLE
Should we investigate if there is a way to auto exclude checkout.bootstrap.js from cache

### ISSUE THREAD

**Issue by NiklasHogefjord** [krokedil/klarna-checkout-for-woocommerce#118]
We've had a couple of support tickets where the file (https://a.klarnacdn.net/kcoc/181024-f5f3b70/checkout.bootstrap.js) have been served from disk and not from Klarnas CDN.

**Comment by NiklasHogefjord** [comment]
This causes the Ooops error message. Lately it was a a conflict with the WP Rocket caching plugin.

**Comment by MichaelBengtsson** [comment]
This was not the cause of the Ooops error message. Closing this for now.
