### ISSUE TITLE
Color Settings: CSS - Problem - Can we automatically add a # if it's missing when saving the settings?

### ISSUE THREAD

**Issue by boozebrorsan** [krokedil/klarna-checkout-for-woocommerce#119]
**CSS-problem in the settings**

Can we automatically add a # if it's missing when saving the settings?

When typing in for example: FFFFFF 
and save, the checkout crashes.

If I add #FFFFFF (or just save again as the color setting adds a # automatically **_after_** its saved the first time)
and save it's working fine.

**Comment by NiklasHogefjord** [comment]
Fixed in 8cca5891573d2b260808110c77832917b4bda295 & 79b09782c4e93371896f8748760263296f1ce657. In Develop branch at the moment but should be included in next release.
