### ISSUE TITLE
Naming of payment gateway id for KCO

### ISSUE THREAD

**Issue by NiklasHogefjord** [krokedil/klarna-checkout-for-woocommerce#12]
Should we keep it as _klarna_checkout_for_woocommerce_?

It is a payment gateway for WooCommerce so it feels like a long name with more info than needed. But since the old plugin use _klarna_checkout_ I understand that we need another name for it.

I just want to raise the question and get your thoughts on it :)

**Comment by slobodan** [comment]
It's a good question to ask, and I don't have a good answer :)

The plugin should keep the name for sure, but gateway doesn't. 

`kco`?

**Comment by kristibarbosky** [comment]
Per discussion during weekly status call on Dec. 7th, please change the gateway ID from klarna_checkout_for_woocommerce to kco.
