### ISSUE TITLE
KCO Global - orders with US addresses placed using an EU store are saved with incorrect _wc_klarna_country

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#120]
Using KCO Global, orders with a US address placed using an EU store are saved with incorrect _wc_klarna_country (US).  Thus, captures fails for these orders.

Example: https://wp-kco.mageklarna.com/wp-admin/post.php?post=630&action=edit

![image](https://user-images.githubusercontent.com/15654455/47851005-a90bbe80-ddad-11e8-9ac8-10dcb7377561.png)

![image](https://user-images.githubusercontent.com/15654455/47851029-c04aac00-ddad-11e8-8b3a-41e87c2d7667.png)

**Comment by kristibarbosky** [comment]
Not sure if this is related to above issue (so if not, I can create a new ticket), but also found this KCO Global test case that isn't working correctly:
Place an order using a Norwegian address, see: https://wp-kco.mageklarna.com/wp-admin/post.php?post=642&action=edit
Then (in the same browser), place a 2nd order using a US address.  The order gets stuck in "Pending Payment" status in Woo because the shipping costs on the Klarna order weren't updated as they should have been and don't match the Woo order's shipping cost, see https://wp-kco.mageklarna.com/wp-admin/post.php?post=643&action=edit
WooCommerce total and Klarna total do not match. Klarna order total: 3500. Order status changed from Processing to On hold.

![image](https://user-images.githubusercontent.com/15654455/47918715-c01ce000-de83-11e8-9712-d846727c5a3e.png)

**Comment by MichaelBengtsson** [comment]
Fixed in 5336529ac04bda52d3ae4360b84db842714a22d0.
