### ISSUE TITLE
Quickly changing the number of items in cart on the checkout page creates a difference between Klarna and Woo

### ISSUE THREAD

**Issue by forsvunnet** [krokedil/klarna-checkout-for-woocommerce#122]
Related to #106, and possibly related to #42.

**Steps to reproduce:**

- Add 2 quantity of any product to cart.
- Go to the checkout page.
- Quickly change the quantity from 2 to 1 and back to 2.

**Expected behaviour:**
When the checkout updates the order total should reflect 2 items in the Klarna checkout window.

**Actual behaviour:**
The WooCommerce order total is correct, but the Klarna iframe total is for 1 item.

![image](https://user-images.githubusercontent.com/799281/47991539-b943d680-e0ea-11e8-9b22-a88b43835be5.png)

**Comment by forsvunnet** [comment]
Note: It takes me a few tries. Most of the time it corrects itself, but for some reason there is a window of about 0.25 seconds where this is possible.

**Comment by NiklasHogefjord** [comment]
Sorry @forsvunnet fot the late reply in this matter. I think that this is actually solved (in commit 6b7c59cb2da3e7c2ac1d9fe62c210830090d5365). This was released in version 1.7.7.

I'm closing this ticket now. Please don't hesitate to reopen it if you still are able to reproduce the issue.
