### ISSUE TITLE
Bad value: total_tax_amount when item tax_rate differs from set shipping tax_rate

### ISSUE THREAD

**Issue by ellinokon** [krokedil/klarna-checkout-for-woocommerce#130]
Experiencing the error `Bad value: total_tax_amount` when first item in cart has a different `tax_rate` than the rate set for shipping. In my specific case it is 15% for food items, and 25% for everything else (that includes shipping).

In my case, shipping has a flat tax rate (49NOK total, 25% is vat), and should not differ pending on contents of the cart. Obviously this causes Klarna API to freak out when it expects both rate and totals to add up properly.

I have tracked the error down to your latest changes [in this file](https://github.com/krokedil/klarna-checkout-for-woocommerce/blob/14ce75aec6d0402a0304a5513d20dac3a9883bf7/includes/class-klarna-checkout-for-woocommerce-order-lines.php#L587).

Choosing the first item in the cart for figuring out the proper `tax_rate` appears to me as a disaster waiting to happen. I am currently unsure if Woocommerce have a simple method for gathering the actual tax rate for the shipping class, but something like the below pseudocode should steer us clear of any problems:

```
base_shipping = total_shipping - total_shipping_tax_amount
rate = round((total_shipping / base_shipping), 2)
tax_rate_klarna = (rate - 1) * 100 * 100
```

Edit:
Here is the data sent to Klarna.
```
    {
      "type": "shipping_fee",
      "reference": "flat_rate:3",
      "name": "Fastpris",
      "quantity": 1,
      "unit_price": 4900,
      "tax_rate": 1500,
      "total_amount": 4900,
      "total_tax_amount": 980
    },
```

Base cost is set to 39,20NOK. Adding 9,80NOK to the base gives us 49,00NOK, which is obviously not a 15% rate.

**Comment by ellinokon** [comment]
It appears to me that `$_tax->get_shipping_tax_rates()` will always get the proper tax rate. Even when all tax rates are set usable by shipping in the different tax classes. This might be something to investigate further.

**Comment by NiklasHogefjord** [comment]
Yes you're right @ellinokon. I've reverted this logic now and use a calculation model we've had in previous versions (see the commit here: 27f79151a4c1c8a4276f5247420bec28086b5cbe).

If you download the Develop version I think that it will work better now. I hope to release this fix (among wit a couple of other fixes) on Monday.

**Comment by NiklasHogefjord** [comment]
Version 1.7.6 is released and available on wordpress.org now. I'm closing this issue. Feel free to re-open it if you still are experiencing problems.
