### ISSUE TITLE
Virtual subscription recurring / renewal orders fail

### ISSUE THREAD

**Issue by kanban-agency** [krokedil/klarna-checkout-for-woocommerce#139]
**Steps to reproduce:**

- Complete the checkout for a **virtual** subscription product
- Wait for renewal to be triggered or trigger renewal manually via scheduled actions

**Expected behaviour:**

- When the renewal payment gets triggered, a transaction should be generated on Klarna side and payment should go through

**Actual behaviour:**

- Renewal payment fails with code 400 and subscription is not renewed

**Debug info:**

Renewal order fails due to API error

`"error_code" : "BAD_REQUEST",
"error_messages" : [ "Bad value: order_lines[1].name" ]`

`"order_lines":[{"name":"REDACTED","quantity":2,"total_amount":2990,"unit_price":1495,"total_tax_amount":477,"tax_rate":1900},{"name":"","quantity":1,"total_amount":0,"unit_price":0,"total_tax_amount":0,"tax_rate":0}]`

**Reasons:**

The following function presumes that `$order->get_shipping_method()` will always return a shipping method name, which doesn't happen for subscription orders that only have virtual products:

[https://github.com/krokedil/klarna-checkout-for-woocommerce/blob/53295c7c6a2e983c57bc28575e334bb441763149/includes/class-klarna-checkout-for-woocommerce-order-lines-from-order.php#L30](https://github.com/krokedil/klarna-checkout-for-woocommerce/blob/53295c7c6a2e983c57bc28575e334bb441763149/includes/class-klarna-checkout-for-woocommerce-order-lines-from-order.php#L30)

The following line adds the offending line item which does not validate on Klarna API because it is forcibly constructed even when shipping is not present and thus "name" is empty:

[https://github.com/krokedil/klarna-checkout-for-woocommerce/blob/53295c7c6a2e983c57bc28575e334bb441763149/includes/class-klarna-checkout-for-woocommerce-api.php#L803](https://github.com/krokedil/klarna-checkout-for-woocommerce/blob/53295c7c6a2e983c57bc28575e334bb441763149/includes/class-klarna-checkout-for-woocommerce-api.php#L803)

**Comment by NiklasHogefjord** [comment]
Hi @kanban-agency,
Thank you for a **very** good issue report! :)

This should have been fixed in bb57eccf65808e09222c153108803e64a941ea7f and is now available in version 1.7.8.

I'm closing this issue now but please feel free to re-open it if it doesn't solve your problem.

**Comment by ToxicTree** [comment]
This problem started again when the fix was removed in this commit 35081a2
Pleace fix it and update the plugin again.

**Comment by NiklasHogefjord** [comment]
@ToxicTree We should have a fix for this in the Develop branch now. You can test it right away if you want to use that branch. Otherwise we will be releasing an update within the next few days.
