### ISSUE TITLE
Remove filter

### ISSUE THREAD

**Issue by wahlly** [krokedil/klarna-checkout-for-woocommerce#143]
Is there any way this could be optional:
add_filter( 'woocommerce_checkout_cart_item_quantity', array( $this, 'add_quantity_field' ), 10, 3 );
If not can someone help me with a remove:_filter that works.

**Comment by NiklasHogefjord** [comment]
Hi @wahlly,
We are in the process of moving this feature into a separate plugin. Until this is done (estimated to release in the end of January), you can use the following code (in your themes functions.php or in a functionality plugin):

`add_action('init', 'krokedil_remove_quantity_field');

function krokedil_remove_quantity_field() {
	remove_filter( 'woocommerce_checkout_cart_item_quantity', array( Klarna_Checkout_For_WooCommerce::get_instance(), 'add_quantity_field' ), 10, 3 );
}`

**Comment by wahlly** [comment]
Takk 👍
