### ISSUE TITLE
AN ERROR OCCURRED DURING COMMUNICATION WITH KLARNA (BAD VALUE: TOTAL_TAX_AMOUNT).

### ISSUE THREAD

**Issue by fracii** [krokedil/klarna-checkout-for-woocommerce#144]
I get this error. 

AN ERROR OCCURRED DURING COMMUNICATION WITH KLARNA (BAD VALUE: TOTAL_TAX_AMOUNT).

**Comment by kristibarbosky** [comment]
@fracii - In the WooCommerce settings, how many decimals do you have it set to display? We currently need this to be set to 2 decimals for calculations to work properly, but we are working to possibly support 0 decimals, see: [(https://github.com/krokedil/klarna-checkout-for-woocommerce/issues/38)]

If this does not resolve your problem, you can review the Klarna merchant portal to see your Logs to provide additional information, such as the request body of the merchant_create_order_v3 and details of your tax settings for your store.

**Comment by NiklasHogefjord** [comment]
I'm closing this issue now. Please feel free to re-open it if you have any follow up questions.
