### ISSUE TITLE
Add setting for making phone number mandatory in Germany

### ISSUE THREAD

**Issue by NiklasHogefjord** [krokedil/klarna-checkout-for-woocommerce#146]
I can't find this feature in developers.klarna.com but for Germany it seems as phone number is optional. @kristibarbosky is there a way to make phone number mandatory similar to phone_mandatory in KCO v2 (https://developers.klarna.com/en/se/kco-v2/checkout-api/#options-object-properties)?

**Comment by kristibarbosky** [comment]
@NiklasHogefjord - I have not yet personally tested but I find a ticket that states that phone_mandatory is available for KCOv3, but it is just not yet documented:
 
It can be specified in the options like shown here:

"options":

{       "phone_mandatory":true   }
,
The default value (when not specified) is false, meaning phone not mandatory.

**Comment by djdwarf69** [comment]
I also wan't to make the phone field mandatory.
Where do I have to add this options to do so?

**Comment by Kristian-Andersson** [comment]
44a61b2e352571a7d4e88be79d154faee0b8b3ba
