### ISSUE TITLE
Error when purchasing variable product with virtual variants

### ISSUE THREAD

**Issue by samuellinde** [krokedil/klarna-checkout-for-woocommerce#147]
We're having issues when a customer tries to purchase a variable product with virtual variants.

It's related to #84, but that issue seems to have been fixed. However, that doesn't seem to take into account variable products. But the error is the same, with checkout halting because shipping options isn't selected.

**Comment by NiklasHogefjord** [comment]
Hi @samuellinde,

Sorry for the late reply. I will look into this and will try to get back during this week.

**Comment by NiklasHogefjord** [comment]
Hi @samuellinde,
We found a bug and fixed it here: https://github.com/krokedil/klarna-checkout-for-woocommerce/commit/221eaf0d6194fa613ca548ef8873ae21117c1d4f. 

This fix is now available in the 1.8.1 version (https://github.com/krokedil/klarna-checkout-for-woocommerce/releases/tag/1.8.1).
