### ISSUE TITLE
Always include redirect header location for 303 validation [PI-594]

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#149]
There can be some cases (e.g. "Error message: An account is already registered with your email address. (Please login). Please verify the order with Klarna.") where the Woo store returns a 303 response to the VALIDATION callback without a redirect header location.  Please always return a redirect header location so that customers don't get to the Woo confirmation page if they shouldn't.

see: https://github.com/krokedil/klarna-checkout-for-woocommerce/blob/master/includes/class-klarna-checkout-for-woocommerce-api-callbacks.php#L321-L343

      "name" : "Klarna-Correlation-Id",
        "value" : "2eb1c90b-f32f-4e43-9925-95b8bcdd91b4"
      } ]
    },
    "merchant_response" : {
      "body" : "",
      "headers" : [ {
        "name" : "Server",
        "value" : "nginx/1.14.1"
      }, {
        "name" : "Content-Type",
        "value" : "text/html; charset=UTF-8"
      }, {
        "name" : "Transfer-Encoding",
        "value" : "chunked"
      }, {
        "name" : "Connection",
        "value" : "keep-alive"
      }, {
        "name" : "Date",
        "value" : "Sun, 23 Dec 2018 21:59:35 GMT"
      }, {
        "name" : "X-Page-Speed",
        "value" : "1.13.35.2-0"
      }, {
        "name" : "Cache-Control",
        "value" : "max-age=0, no-cache, must-revalidate"
      } ],
      "http_status_code" : 303
    },
    "error_message" : "Rejected approval without providing a redirect URI in Location header"

**Comment by NiklasHogefjord** [comment]
Should be fixed in https://github.com/krokedil/klarna-checkout-for-woocommerce/commit/e44398df1185f6faa56b3aa84a3ba0124a292794
