### ISSUE TITLE
For DE/AT, the option to show the legal text covering prefill should be a configurable option

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#15]
The plugin currently shows the prefill legal text as described below.  This ticket requests that this functionality is configurable, per:

https://developers.klarna.com/en/de+php/kco-v2/prefill

**Comment by kristibarbosky** [comment]
already done (but only shown if store base address is German or Austria):
![image](https://user-images.githubusercontent.com/15654455/34383572-060b0aa4-eae4-11e7-826e-cf90bc80c6bc.png)

**Comment by slobodan** [comment]
@kristibarbosky can we close this one then?

**Comment by kristibarbosky** [comment]
![image](https://user-images.githubusercontent.com/15654455/35923681-ec46244c-0bee-11e8-8004-f0971aa6c138.png)
