### ISSUE TITLE
Works in test mode active but in live mode it gets error on line 328 Message Uncaught Error: Cannot use object of type WP_Error as array in

### ISSUE THREAD

**Issue by fracii** [krokedil/klarna-checkout-for-woocommerce#157]
Fatal Error
Line 328
Message Uncaught Error: Cannot use object of type WP_Error as array in private_html/wp-content/plugins/klarna-checkout-for-woocommerce/includes/class-klarna-checkout-for-woocommerce-api.php:328 Stack trace: #0 
private_html/wp-content/plugins/klarna-checkout-for-woocommerce/includes/klarna-checkout-for-woocommerce-functions.php(10): Klarna_Checkout_For_WooCommerce_API->get_order() #1 private_html/wp-content/plugins/klarna-checkout-for-woocommerce/templates/klarna-checkout.php(30): kco_wc_show_snippet() #2 private_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(211): include('/home/sortera/d...') #3 private_html/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-checkout.php(283): wc_get_template('checkout/form-c...', Array) #4 private_html/wp-content/
File private_html/wp-content/plugins/klarna-checkout-for-woocommerce/includes/class-klarna-checkout-for-woocommerce-api.php

**Comment by NiklasHogefjord** [comment]
This should be fixed in 77857e2297bd8f6aaca2e470de63d105152aad30. It is available in the Develop branch. We will test this closer and release it later this week.

**Comment by fracii** [comment]
Ok, thx I can also test this.

**Comment by fracii** [comment]
> This should be fixed in [77857e2](https://github.com/krokedil/klarna-checkout-for-woocommerce/commit/77857e2297bd8f6aaca2e470de63d105152aad30). It is available in the Develop branch. We will test this closer and release it later this week.

It working but not tested to get any orders yet .But I think this going to work also. Thank you!

**Comment by MichaelBengtsson** [comment]
Closing this since it seems to be resolved.
