### ISSUE TITLE
uptime robot feature request

### ISSUE THREAD

**Issue by Tobias-Conrad** [krokedil/klarna-checkout-for-woocommerce#158]
As it could happen that the plugin or klarna or i could harm the installation and could break the checkout from working. i would suggest to create some string uptimerobot could track and if not there can alert me via email, sms.

as we need a product in cart to show the checkout i would suggest a widget shown o webpage when checkout it working.

please find a solution,....

**Comment by NiklasHogefjord** [comment]
Sorry for the late reply.

This is not anything we will solve in the KCO plugin. In the future we might offer this as some kind of addon solution but for the moment I recommend that you take a look at a service similar to https://ghostinspector.com/.
