### ISSUE TITLE
Support hooks to merchant to add EMD (extra merchant data)

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#159]
Some merchants may be required by Klarna to submit EMD with their KCO orders.  The merchant will need to do the work to add their specific EMD data, but can we provide hooks or such to easily enable the merchant to do so?

For more info, see:
https://developers.klarna.com/en/gb/kco-v3/checkout/extra-merchant-data/

https://developers.klarna.com/api/#checkout-api__create-a-new-order__attachment

**Comment by NiklasHogefjord** [comment]
We already have hooks that is available for this, but we need to explain more in detail how to use them.

We did start with a gist for EMD that initially was required for digital/virtual products. That ended up in not being required, but I think that we can use that as a starting point: https://gist.github.com/krokedilgists/3247e308b7fbcc8c96884dc8a1c202c6.

@kristibarbosky do you have a specific kind of product type where this is a requirement? It would be good to be able to use a real world example.

**Comment by kristibarbosky** [comment]
Klarna product team confirmed EMD will still be requested for KCOv3 recurring as:

SUBSCRIPTION (subscription) and CUSTOMER ACCOUNT INFO (customer_account_info)
--
Variable name | Explanation | Variable value
StartTime | Name of the voucher sold | 2012-01-24T15:00
EndTime | Date and time when the subscription ends (local) ISO8601 | 2012-01-24T15:00
UniqueAccountIdentifier | Unique name / number to identify the specific customer account | 123456
AccountRegistrationDate | Date and time when the customer has created the account (local) ISO8601 | 2012-01-24T15:00

**Comment by kristibarbosky** [comment]
this is in discussion with Klarna product about what EMD should be required for new customers/orders; in the meanwhile, merchants could request a waiver from merchant underwriting regarding this.

**Comment by kristibarbosky** [comment]
EMD is now supported within the latest plugin for recurring/subscriptions; any other EMD packages are up to the merchant to customize
