### ISSUE TITLE
DE/AT - cancellation_terms_uri

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#16]
Add config option - available for DE & AT countries cancellation_terms URL
https://developers.klarna.com/api/#checkout-api__create-a-new-ordermerchant_urls__cancellation_terms

(This should now be available in production for KCOv3)

**Comment by NiklasHogefjord** [comment]
@kristibarbosky How is this url supposed to be used? Is it mandatory in DE & AT to have a separate page containing information about how to cancel an order?

**Comment by kristibarbosky** [comment]
@NiklasHogefjord - this should work the same in KCOv3 as it does currently with KCOv2.  

This is the best info I could find on how it should work:


The terms and conditions of merchant_terms and the checkout_terms apply. Right of revocation_information

So basically it he merchant provides this : cancellation_terms_uri and Klarna will link to that otherwise we will link to merchant terms url appending #cancellation_right
 
ex. terms_uri#cancellation_right
 
This is the section Right of revocation_information

**Comment by NiklasHogefjord** [comment]
OK, thanks for the info @kristibarbosky.

So the best way would be to add this as a setting field that's only applicable for DE & AT? Similar to how we do it with _Show prefill consent notice_ (that is only available for DE & AT)?

**Comment by kristibarbosky** [comment]
@NiklasHogefjord - yes, agreed, it should be similar to DE/AT prefill consent notice.  thx.

**Comment by NiklasHogefjord** [comment]
Thanks @kristibarbosky, looking into this in the beginning of next week if that's ok?

**Comment by kristibarbosky** [comment]
Next week is fine @NiklasHogefjord, thanks!

**Comment by kristibarbosky** [comment]
For KCOv3, this is documented at: https://developers.klarna.com/api/#checkout-api__create-a-new-ordermerchant_urls__cancellation_terms

**Comment by kristibarbosky** [comment]
Per discussion today with Klarna & Krokedil, best architecture for this is documentation for implementation with custom code (using a Woo filter), not as a config option in the Woo plugin.

**Comment by NiklasHogefjord** [comment]
Information on how to add this via a separate filter is now documented here: https://docs.krokedil.com/article/143-klarna-checkout-hooks-action-filter#h-H2_9.
