### ISSUE TITLE
Tickbox editable, right hook in place and remove

### ISSUE THREAD

**Issue by Tobias-Conrad** [krokedil/klarna-checkout-for-woocommerce#161]
Hello,

Still open since 30.01.2019 via Mail!
After you removed germanized tickbox code i added it manually.
Now i have 2 tickboxed one editable from germanized in wrong place and one inside iframe i can not edit or remove:

Tickbox solution is here:
Please remove not editable tick box inside klarna iframe (kco_wc_show_snippet())

and place germanized text above the buy now button and cart summarize, 
as the klarna law text is there already.(please add hook and update gist snipped https://gist.github.com/krokedilgists/7fab7cf5d6a7b3c52fdd6bbc641592d0)

Also look if the germanized text on normal checkout is in same position too.

source: 
https://github.com/krokedil/klarna-checkout-for-woocommerce/blob/master/templates/klarna-checkout.php
https://docs.woocommerce.com/document/klarna-checkout-hooks-actions-filters/ (shows legal text below button, not good!)

Please see screencast for details:
https://screencast-o-matic.com/watch/cqVv3u3a8D

Thank you

Tobias

**Comment by MichaelBengtsson** [comment]
Closed since i belive this was resolved in a support ticket you had with us. If this is incorrect then please reopen this issue.
