### ISSUE TITLE
Provide admin notice (via KCO plugin) to inform merchants to update their EPM plugin (if used)

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#165]
Per recent release of the Klarna External Payment (EPM) method plugin
https://github.com/krokedil/klarna-checkout-external-payment-method-for-woocommerce

can we inform merchants (that have the EPM plugin active) with an admin notice to inform them that they should update the EPM plugin?

(Can we also document exactly which release of the KCO plugin breaks the EPM flow?)

**Comment by NiklasHogefjord** [comment]
@kristibarbosky we can add an update mechanism for future releases, not the current version installed on merchant sites.

**Comment by kristibarbosky** [comment]
That would be great, thanks!

**Comment by NiklasHogefjord** [comment]
Fixed in 74f22e0d10a979fb1dcd6713f2acde5e5a903b38 and released in v2.0.
