### ISSUE TITLE
Unable to purchase: "No shipment selected" when mix of virtual and physical products

### ISSUE THREAD

**Issue by orjansteffensen** [krokedil/klarna-checkout-for-woocommerce#166]
First of all: I am not sure if this error is due to the KCO-plugin, but it is very similiar to this one which I posted some time ago. https://github.com/krokedil/klarna-checkout-for-woocommerce/issues/84

The main difference now is that if I purchase a virtual product by itself everything works as it should, but if I try to purchase both a virtual AND a physical product, then I will get the "No shipment selected" message, and cannot complete the order.

**Comment by NiklasHogefjord** [comment]
Hi @orjansteffensen,
Sorry for the very late reply in this issue.

I got a fix in the Develop branch that should work for you now. We will release this in a new version within a few days but if you want to use it right away it you can just download the Develop version.

**Comment by jonasostrom** [comment]
Same here and in my DEV env I always get this error log warning when checkout with KCO:
Note: It's after the checkout is completed and the checkout does not break.
`
 PHP Notice:  Undefined index: shipping_method in plugins/woocommerce/includes/class-wc-checkout.php on line 856
`

**Comment by NiklasHogefjord** [comment]
This should be fixed in 362b8f0f99fbd011f285d485a691c9e6566e65bf and is now available in [version 1.9.0](https://github.com/krokedil/klarna-checkout-for-woocommerce/releases/tag/1.9.0).
