### ISSUE TITLE
Support Klarna Shipping Service (with TMS integration)

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#167]
After https://github.com/krokedil/klarna-checkout-for-woocommerce/issues/68 is complete,

For testing KSS, PK06216 can be used.

**Comment by kristibarbosky** [comment]
In addition to accept the order with shipping options provided from the TMS (but not necessarily defined within Woo), additional fields should also be sent into Klarna: https://developers.klarna.com/api/#checkout-api__create-a-new-order__order_lines__shipping_attributes

**Comment by MichaelBengtsson** [comment]
This is now supported with the latest release of KCO and KOM.
