### ISSUE TITLE
Shipping doesn't show when hidding shipping costs until an address is entered

### ISSUE THREAD

**Issue by a-larsson** [krokedil/klarna-checkout-for-woocommerce#170]
In the Checkout it doesnt update/show the shipping cost correct if this setting is chosen in the WooCommerce Shipping options:

![skarmavbild 2019-02-22 kl 17 13 41](https://user-images.githubusercontent.com/2573170/53255301-a3701680-36c5-11e9-9d74-70519d61d6a3.png)

**_Hide shipping costs until an address is entered_**

If you deactivate it, it works as it should:

![skarmavbild 2019-02-22 kl 17 13 53](https://user-images.githubusercontent.com/2573170/53255328-b1be3280-36c5-11e9-8234-abbc4d876462.png)

**Comment by MichaelBengtsson** [comment]
Closing this since this has been fixed.
