### ISSUE TITLE
Support for multiple currency switcher plugins [PI-692]

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#171]
While KCO (& KP) currently work well with the Aelia currency switcher (as documented at: https://docs.woocommerce.com/document/klarna-checkout/#section-8), could the plugins also be compatible with other common currency swtichers (such as [WMPL ](https://wpml.org/documentation/related-projects/woocommerce-multilingual/multi-currency-support-woocommerce/) and WooCommerce Currency [Switcher)](https://wordpress.org/plugins/woocommerce-currency-switcher/)

**Comment by kristibarbosky** [comment]
This ticket would apply to both KCO & KP.

**Comment by tlygnersjo** [comment]
Any news about this? I would also see support for currency switchers (like WPML multi-currency).

**Comment by MichaelBengtsson** [comment]
@tlygnersjo We now have a better support for this in the latest release. However there are still some things that needs to be resolved. But atleast now you should be able to take orders with WPML.

**Comment by tlygnersjo** [comment]
@MichaelBengtsson Thanks!

**Comment by NiklasHogefjord** [comment]
Tested and working with [WOOCS - WooCommerce Currency Switcher](https://sv.wordpress.org/plugins/woocommerce-currency-switcher/) (the plugin @kristibarbosky mentioned higher up in this thread).

**Comment by NiklasHogefjord** [comment]
Tested and working with [WooCommerce Multilingual – run WooCommerce with WPML](https://sv.wordpress.org/plugins/woocommerce-multilingual/). It would be great if you can double check this @Kristian-Andersson before we add it to the docs.

**Comment by MichaelBengtsson** [comment]
This has now been tested. We will add these plugins to our docs as supported plugins.
