### ISSUE TITLE
Should orders created via fallback trigger order to Processing status? [PI-587]

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#172]
If orders don't go thru Processing status, emails are not generated.

**Comment by MichaelBengtsson** [comment]
Yes it should, this has been added to develop now.

**Comment by bretweinraub** [comment]
Any time frame for release?  Asking for a friend :)

**Comment by NiklasHogefjord** [comment]
Hi @bretweinraub, sorry for the late reply.

We have released [version 1.9.0](https://github.com/krokedil/klarna-checkout-for-woocommerce/releases/tag/1.9.0) now with this fix included.
