### ISSUE TITLE
Plugin conflict with WooCommerce PickingPal

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#173]
The Klarna Checkout plugins has some sort of conflict with the WooCommerce PickingPal plugin. Fortunately our client didn't need that plugin, so we've disabled it and everything seems to be working again!

**Comment by MichaelBengtsson** [comment]
Sorry for the late reply. But do you know what the error or conflict was more exactly? Also do you have a link to the plugin itself? I can only seem to find the documentation on the WooCommerce website.

**Comment by kristibarbosky** [comment]
We do not have a copy of the plugin to debug, so closing this ticket as the merchant didn't need this plugin anymore.

Plugin info: https://docs.woocommerce.com/document/woocommerce-pickingpal/ and https://pickingpal.com/shop/
