### ISSUE TITLE
Improve error messaging for when order is not found for Klarna GET

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#174]
Current error message: "An error occurred during communication with Klarna (Klarna order ID is missing)" is resulting in questions/tickets from customers and merchants about this.

**Comment by NiklasHogefjord** [comment]
Fixes done in 95912ea009fe1b954bfbbdb372dce0572dd88978 & 608f8165a63eeeae1c3e25495736822bf6446fc2

**Comment by NiklasHogefjord** [comment]
We also included a check in _wp_footer()_ on checkout page to determine if the KCO template page has been loaded. If KCO is the selected payment gateway and the template should have been loaded, but didn't - then redirect the customer to cart page with the message _Failed to load Klarna Checkout template file._

These updates are now available in [version 1.9.0](https://github.com/krokedil/klarna-checkout-for-woocommerce/releases/tag/1.9.0). I'm closing this issue now but we can re-open it again if needed.
