### ISSUE TITLE
Add support for MailChimp plugins

### ISSUE THREAD

**Issue by NiklasHogefjord** [krokedil/klarna-checkout-for-woocommerce#176]
Mailchimp for WooCommerce
https://sv.wordpress.org/plugins/mailchimp-for-woocommerce/

Mailchimp for WordPress
https://sv.wordpress.org/plugins/mailchimp-for-wp/
(also the pro-version)

Also check so this works:

* Newsletter checkbox in the Checkout
* Abandon Cart function

**Comment by MichaelBengtsson** [comment]
For Mailchimp For WooCommerce the Abandoned cart should work from a previous update that we have done.

**Comment by Jitan** [comment]
Hi, I would like to integrate Mailchimp for Woocommerce with Klarna Checkout. Do you have a suggestion of where / how to add the checkbox to the checkout?

**Comment by MichaelBengtsson** [comment]
@Jitan We will have a code example for how to do this soon on our gists. When we have it up i can update this issue with a link to that page. I will see if i can get it sorted this comming monday.

**Comment by MichaelBengtsson** [comment]
@Jitan Here is a link to a Gist example for how to get the checkbox added inside of the Klarna Checkout iFrame.
https://gist.github.com/krokedilgists/ae9b94475e8e7986ccca8903ec3e8aa7

I will close this issue now since we seem to be able to full support this at this point.
