### ISSUE TITLE
Bad value: order_tax_amount when renewing virtual subscriptions

### ISSUE THREAD

**Issue by josmase** [krokedil/klarna-checkout-for-woocommerce#177]
**Steps to reproduce:**

- Complete the checkout for a virtual subscription product
- Wait for renewal to be triggered or trigger renewal manually via scheduled actions

**Expected behaviour:**

- When the renewal payment gets triggered, a transaction should be generated on Klarna side and payment should go through

**Actual behaviour:**

- Renewal payment fails with code 400 and subscription is not renewed

**Debug info:**

`{"order_amount":4000,"order_lines":[{"name":"Yogaworld - Plus","quantity":1,"total_amount":4000,"unit_price":4000,"total_tax_amount":666,"tax_rate":2000}],"purchase_currency":"SEK","order_tax_amount":700}"}`

`"error_messages" : [ "Bad value: order_tax_amount" ]`

**Reasons**

In #38 this problem was fixed for normal checkout. But when renewal orders are created the `order_tax_amount` is calculated from the `order_tax_amount` of that previous order. The problem is that the following line returns a rounded tax amount.

https://github.com/krokedil/klarna-checkout-for-woocommerce/blob/454e73001a53f229a351ac79d72c98fd29cb34c5/includes/class-klarna-checkout-for-woocommerce-order-lines.php#L147

This causes the value from following line to return a rounded value that is not the same as the individual line items total tax amount.

https://github.com/krokedil/klarna-checkout-for-woocommerce/blob/454e73001a53f229a351ac79d72c98fd29cb34c5/includes/class-klarna-checkout-for-woocommerce-order-lines-from-order.php#L14 

 Renewal works fine if i  remove `round()` before making the original purchase.

**Comment by MichaelBengtsson** [comment]
@josmase We have a fix for this now in our develop branch of the plugin after the aa2005badeccb1265eb79da932e039770bba7942 commit. You can test it for yourself and see if that solves your issue. We will be releasing this in a few days after we test this and a few other things more thoroughly.

**Comment by josmase** [comment]
@MichaelBengtsson This fix does not seem to work as i still get the same error. The problem is that the `order_tax_amount` is still 700 when the `total_tax_amount` for the line item is 666. I tried moving the `round()` calls to before taking the value  *100, in order to make the `total_tax_amount` 700. But then i got `[ "Bad value: order_lines[0].total_tax_amount" ]`. Which i assume is because of the `total_tax_amount`and `tax_rate` not matching.

**Comment by MichaelBengtsson** [comment]
@josmase Sadly at the moment our credentials are not working for recurring orders, so i was unable to test this fully myself. However ill keep looking at this and see if we can find a fix for this. The fix we did today weas to bring this inline with how we do it in other parts of the plugin, hoping that it would solve the issue.

I will look at this some more today and tomorrow and see if i can find a solution.

**Comment by NiklasHogefjord** [comment]
Tested now and for me it's working with [version 1.9.0](https://github.com/krokedil/klarna-checkout-for-woocommerce/releases/tag/1.9.0).

Please feel free to re-open this issue if the issue consists after you've tested with v1.9.0.

**Comment by josmase** [comment]
Tested and working for me.
