### ISSUE TITLE
Wrapper class rather than inline style (kco_wc_show_another_gateway_button)

### ISSUE THREAD

**Issue by tlygnersjo** [krokedil/klarna-checkout-for-woocommerce#178]
It would be great if you could add a class on the "select another payment option" button wrapper (<p style="margin-top: 30px"></p>) rather than inline style. This will make it much easier and failproof to style the wrapper.

Is that something that can be fixed?

**Comment by MichaelBengtsson** [comment]
Yes this is something we can change! I have made a commit for this in the develop branch of the plugin right now. 750660596617d906acc5775330ec94fe80a3f9a8
