### ISSUE TITLE
B2B checkout (missing company name field)

### ISSUE THREAD

**Issue by tlygnersjo** [krokedil/klarna-checkout-for-woocommerce#179]
Hi,

I'm currently developing a ecommerce with KCO for WooCommerce with a developer test account at Klarna. I've selected B2B only for KCO and when i select Klarna as payment method i can't see any field for company name ($fields['company']) in neither custom extra fields or in KCO iframe.

Do you know if this has to do with being in "test mode" or a bug (either in my theme or in your plugin)?

**Comment by tlygnersjo** [comment]
This how it looks like:
![b2c_kco](https://user-images.githubusercontent.com/5164069/54272248-90918900-4583-11e9-924e-a4e5989ff725.png)

**Comment by tlygnersjo** [comment]
It probably should look more like this:
![Skärmavbild 2019-03-13 kl  11 28 33](https://user-images.githubusercontent.com/5164069/54272269-9edfa500-4583-11e9-958c-3b8f070c654e.png)

**Comment by MichaelBengtsson** [comment]
@tlygnersjo Do you know if your test account has B2B settup for it? Also we have a setting for what customer type the iFrame should allow in the plugin settings. Can you check that this includes B2B aswell as B2C?

**Comment by tlygnersjo** [comment]
@MichaelBengtsson I have no idea if my account is setup for B2B, how can i check that? Can't find such a setting in Klarna's dashboard (playground).

My setting in the WP plugin is set to "B2B only" as this is what we will be using when the ecommerce are going live.

**Comment by MichaelBengtsson** [comment]
@tlygnersjo This is something that you need to contact Klarna about in that case and ask them to look at your account. Do you have a contact at Klarna to contact? Else i would suggest sending a ticket to their onboarding support. B2B is not something that is on as standard for Klarna, so if you have not asked for it, it is probably not available on your credentials.

You can contact Klarna on this email: Moa.supprt@klarna.com

**Comment by MichaelBengtsson** [comment]
Closing this as this seems to be outside of the plugin. If you need further help please contact us at support@krokedil.se or contact Klarna regarding your account at the mail above.
