### ISSUE TITLE
Some KCO orders are missing the refund button

### ISSUE THREAD

**Issue by michaelmcmillan** [krokedil/klarna-checkout-for-woocommerce#180]
The refund button is not showing on some of our KCO orders. I've noticed that on all orders with a missing refund button, the Klarna ID is also non-clickable. I guess these two things are related, but I'm not sure what's going on.

**Example of KCO order missing refund button**
<img width="1089" alt="missing" src="https://user-images.githubusercontent.com/147197/54281395-f12bc080-4599-11e9-8587-9b09162c7ea2.png">

**Example of KCO order with refund button**
<img width="1091" alt="present" src="https://user-images.githubusercontent.com/147197/54281433-06a0ea80-459a-11e9-9bab-29a0ed476067.png">

Do you have a clue here, @MichaelBengtsson?

**Comment by MichaelBengtsson** [comment]
@michaelmcmillan Hi! The reasson for this is because the first order is set to the status on-hold. If you want to refund this, then i would suggest setting it to processed or activate the order.

However, if the order is set to on-hold that usualy means that it was created on a fallback function. Can you see anything in the order notes?

**Comment by michaelmcmillan** [comment]
Thanks @MichaelBengtsson! I've tried flipping the status from on-hold to processed in the WooCommerce-order, unfortunately to no avail.

This is another order where the refund button is missing, status in set to processing. I've included the order notes below.

<img width="763" alt="Skjermbilde 2019-03-14 kl  12 15 36" src="https://user-images.githubusercontent.com/147197/54352988-2cd69100-4653-11e9-927e-189dbf86e6ce.png">


<img width="250" alt="Skjermbilde 2019-03-14 kl  12 16 12" src="https://user-images.githubusercontent.com/147197/54353006-34963580-4653-11e9-8b1a-5ffe77ff5458.png">

<img width="252" alt="Skjermbilde 2019-03-14 kl  12 15 58" src="https://user-images.githubusercontent.com/147197/54353024-437ce800-4653-11e9-8998-10eb4257aa21.png">

**Comment by NiklasHogefjord** [comment]
Hi,
@michaelmcmillan & @MichaelBengtsson, this question is asked/reported in the wrong repository. 

The plugin repository for Klarna v2 is here: https://github.com/krokedil/woocommerce-gateway-klarna.

To be able to do a refund you need to first activate the order (e.g set the order status to _Completed_.

I'm closing this issue.
