### ISSUE TITLE
Add support for Local Pickup Plus plugin

### ISSUE THREAD

**Issue by Kristian-Andersson** [krokedil/klarna-checkout-for-woocommerce#185]
https://woocommerce.com/products/local-pickup-plus/

Add support for the new feature: "Allow Scheduled Pickup Dates". This option, when activated, will generate a new datepicker field in the checkout page.

**Comment by MichaelBengtsson** [comment]
Closed. Works in the current version of KCO 1.10.3 and version 2.4.3 of the Local pickup plus plugin.
