### ISSUE TITLE
Germanized & Klarna

### ISSUE THREAD

**Issue by taurus-web** [krokedil/klarna-checkout-for-woocommerce#186]
I´m using woocommerce germanized pro and trying to implement klarna now for a long while. actually i got the following error message: legal direct_debit_legal shipping_parcelshop_post_number are missing [https://drive.google.com/file/d/1GAN392i49l_FHezEfnAb_nolyPDv3C21/view?usp=sharing](url)

error message is always the same whether i activate or deactivate parcel shops in germanized. i did not set a differnet delivery adress in the checkout process. what do i have to change to fix this issue?

Many thanks in advance
Tim

**Comment by NiklasHogefjord** [comment]
Hi @taurus-web,
[Version 1.9.0](https://github.com/krokedil/klarna-checkout-for-woocommerce/releases/tag/1.9.0) is available now. We have a fix in how we handle required extra checkout form fields there. 

Perhaps you can try that version and see if it solves your problem?

**Comment by MichaelBengtsson** [comment]
Fixed in the latest version. Please reopen the issue if that is not the case for you.
