### ISSUE TITLE
No shipping rates for US address on KCO (using Printful) when "Default customer location" set to "Geolocate"

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#19]
store is not getting shipping rates for US addresses on KCO page (but does work on woo checkout page)

**Comment by kristibarbosky** [comment]
on the first production order for the new KCOv3 plugin, the customer calculated the shipping on the cart page (using the defaulted California as the state), which sets the address prefill for the checkout, and she didn't update the state from CA to her correct state, so the merchant would like to set the "Default customer location" back to "Geolocate" asap.

**Comment by slobodan** [comment]
@kristibarbosky I tried fetching incomplete Klarna order and getting the state from that object, but it looks like Klarna order state does not change when you change it in the iframe (unlike other fields).

When you change the state in the iframe and then reload the page, it will revert to the old state. Again, changes to other fields will stay when you reload the page.

Can you check if it's supposed to work this way, or if there is another way to grab the state when it is updated in the iframe?

**Comment by slobodan** [comment]
Fixed by switching to `shipping_address_change`.

**Comment by kristibarbosky** [comment]
In order to sufficiently support tax calculations (if the merchant has taxes configured based on billing address), Klarna will need to create a new JS event: billing_address_change.  This is requested via https://jira.int.klarna.net/jira/browse/KCO-188

**Comment by kristibarbosky** [comment]
@slobodan @MichaelBengtsson - the new JavaScript KCO change event, billing_address_change, is available in production as of today

**Comment by slobodan** [comment]
@kristibarbosky what happens when no separate shipping address is used, and then the iframe address is updated? Will that trigger both events?

**Comment by kristibarbosky** [comment]
@slobodan - yes, my testing shows that it does trigger both JS events:

DE store:
![image](https://user-images.githubusercontent.com/15654455/36317446-1d259034-130b-11e8-9ae2-1514f94167e4.png)

US store:
![image](https://user-images.githubusercontent.com/15654455/36317538-5bdd42e0-130b-11e8-8852-9d8994f56ebf.png)

**Comment by MichaelBengtsson** [comment]
@kristibarbosky On the shipping and billing address change events we dont seem to get a State back which we would need in this case.

**Comment by MichaelBengtsson** [comment]
Closed as i belive this has been fixed.
