### ISSUE TITLE
Add "caution" notice to merchant if optimizing or cache plugins are installed

### ISSUE THREAD

**Issue by NiklasHogefjord** [krokedil/klarna-checkout-for-woocommerce#190]

**Comment by MichaelBengtsson** [comment]
From what i can see this has been added. If i am incorrect please reopen.

**Comment by NiklasHogefjord** [comment]
Where is this added? We only have one notice about this and that is for a specific setting in a specific plugin (https://github.com/krokedil/klarna-checkout-for-woocommerce/blob/develop/includes/class-klarna-checkout-for-woocommerce-admin-notices.php#L127).

I think we should discuss this internally and see how we proceed before closing it.
