### ISSUE TITLE
When using Ship to another address - add support for shipping phone and shipping email

### ISSUE THREAD

**Issue by a-larsson** [krokedil/klarna-checkout-for-woocommerce#191]
When using "Ship to another address" - Add support for shipping phone and shipping email so it is available in the order.

**Comment by kristibarbosky** [comment]
just add these fields as post meta fields, but up to the merchant to display these fields where needed

the following code snippet worked for v2 but after switching to v3 (yet)

`// hook`
`add_action( 'woocommerce_admin_order_data_after_shipping_address', 'show_shipping_address_phone_number', 10, 1 );`
`// styling & content`
`function show_shipping_address_phone_number($order)`
`{ echo ''.__('Shipping phone').': ' . get_post_meta( $order->id, '_shipping_phone', true ) . '';`
