### ISSUE TITLE
Support for Klarna Instant Shopping

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#194]
https://developers.klarna.com/documentation/instant-shopping

(While this ticket is logged in the KCO repo, as that is the top prio, after that is working, we should also build & test that the Woo KIS integration could work with KP also.)

For the initial phase of instant shopping, we should start with building support for the product and cart page with highest prio on the product page.   During our build, we should consider how we can later support the instant shopping for onsite landing pages, promotion pages, etc...

**Comment by NiklasHogefjord** [comment]
Klarna Instant Shopping is now available as a plugin here: https://github.com/krokedil/klarna-instant-shopping-for-wordpress

**Comment by kristibarbosky** [comment]
Klarna Instant Shopping is no longer available.  
Express Checkout is available, per: https://docs.klarna.com/express-checkout/
