### ISSUE TITLE
Disable Klarna Checkout in certain cases 

### ISSUE THREAD

**Issue by robbanl** [krokedil/klarna-checkout-for-woocommerce#196]
Is there anyway I can disable Klarna Checkout for a customer depending on some preset value related to that customer / guest? If there is a hook, then I can simply perform my checks (IP, customer attribute, whatever) and disable Klarna Checkout for that customer and instead show the normal checkout.

Thanks in advance!

**Comment by MichaelBengtsson** [comment]
@robbanl Sorry for the late reply to your question.

Yes this is possible with standard WooCommerce functionality. For example you can read this post: https://growdevelopment.com/remove-default-woocommerce-payment-gateways/ that explains how to remove the default gateways, this should be able to be used with some extra logic arround what you need. There are also several plugins that lets you change gateways based on countries and more. For example: https://wordpress.org/plugins/woocommerce-country-based-payments/

Hopefully this solves your issue, if you had not found something else already.

**Comment by Preen** [comment]
This is a working solution:

```
add_filter( 'woocommerce_available_payment_gateways', 'codesmile_kco_disable_manager' );

function codesmile_kco_disable_manager( $available_gateways ) {
   if ( isset( $available_gateways['kco'] ) ) {
      unset( $available_gateways['kco'] );
   }
   return $available_gateways;
}
