### ISSUE TITLE
Credentials check to verify Klarna credentials work for KCOv3

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#197]
To help avoid incompatibilities (like using the KCO plugin when Klarna credentials are configured for KP), could we add functionality to do a basic credentials check (e.g. for KCOv3,  a create_order API call) to verify that the credentials work for the installed plugin?

**Comment by MichaelBengtsson** [comment]
@kristibarbosky In bfe2720e125bb05696eb6234196fe882fc94f358 i added a check to see if the credentials match what is an expected KCO v3 credentail atleast. This should prevent people from trying v2 credentials with KCO v3. However it wont stop KP credentials from being used. We can discuss this a bit more if you want.

**Comment by kristibarbosky** [comment]
included in v2.0.16: https://github.com/krokedil/klarna-checkout-for-woocommerce/releases/tag/2.0.16

related: PI-1066
