### ISSUE TITLE
Enable checkout for 0 value orders to be customizable [PI-688]

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#198]
Currently design is that 0 value orders use Woo checkout (since no payment is taken by Klarna), but enhancement request is to allow merchants to customize the checkout for 0 value orders (to still use Klarna if desired).

**Comment by kristibarbosky** [comment]
this should be an option per merchant

**Comment by MichaelBengtsson** [comment]
Fixed in 0644939a04354c91fa4cc01277816d73cbc6a287

**Comment by kristibarbosky** [comment]
https://github.com/krokedil/klarna-checkout-for-woocommerce/commit/0644939a04354c91fa4cc01277816d73cbc6a287#commitcomment-34601544

You can read about that in our documentation here: https://docs.krokedil.com/article/143-klarna-checkout-hooks-action-filter#h-H2_1
And you can find a code example there as well. It is at the bottom of the page.
