### ISSUE TITLE
Improve handling of KCO iframe on confirmation page [PI-699]

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#202]
To support additional themes (and also cross-sell per https://github.com/krokedil/klarna-checkout-for-woocommerce/issues/137), please kindly improve the way the KCO iframe is handled on the confirmation page.

**Comment by NiklasHogefjord** [comment]
Should be fixed in https://github.com/krokedil/klarna-checkout-for-woocommerce/releases/tag/1.10.0.
