### ISSUE TITLE
Locale issue with KCO

### ISSUE THREAD

**Issue by pastebin** [krokedil/klarna-checkout-for-woocommerce#203]
If not logged in on the site - the Checkout is presented in English - everything on the site is set to Swedish.
Following JS can be seen in the source code for the Checkout.
`LOCALE:'en-US',`

Using 1.9.2 KCO

**Comment by a-larsson** [comment]
@pastebin what setting do you have under the woocommerce settings ----> general ---> Default customer location . ?

**Comment by MichaelBengtsson** [comment]
@pastebin This seems to be an issue with the new version of WooCommerce and how they get the customer data now. We will investigate this a bit more and hopefully have a fix soon.

**Comment by a-larsson** [comment]
Fix has been released in 1.9.3
