### ISSUE TITLE
KCO 1.9.2 breaks with WooCommerce 3.6.2 and redis-cache

### ISSUE THREAD

**Issue by forsvunnet** [krokedil/klarna-checkout-for-woocommerce#204]
WooCommerce 3.6.2 introduced caching of template files. KCO uses a filter on `wooocommerce_locate_template` to override the checkout template conditionally. With cache enabled the cached template (templates/kco-checkout.php) is loaded and the condition is ignored so that the original woocommerce checkout template is never loaded and therefore no orders are created during the checkout process.
The code should be changed to filter `wc_get_template` instead.

**Comment by MichaelBengtsson** [comment]
Thank you @forsvunnet for the commend and the potential fix. We will look into this right away, and hopefully have a fix for this and other issues that came up with 3.6.x.
