### ISSUE TITLE
Translations for Woo KCOv3 admin settings

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#207]
Similar to how previous KCO plugin was translated, will this plugin be translated?

**Comment by MichaelBengtsson** [comment]
@kristibarbosky From what i can see, the settings page is already translated to Swedish, and should be able to be translated by anyone else into other languages for their own use.

Do you mean something different then the gateway settings?

**Comment by kristibarbosky** [comment]
Thanks @MichaelBengtsson -
Confirmed this is good.  
![image](https://user-images.githubusercontent.com/15654455/62301677-06b95e00-b447-11e9-9b2b-74a5cca8a573.png)
