### ISSUE TITLE
Support for German Formal locale

### ISSUE THREAD

**Issue by ahegyes** [krokedil/klarna-checkout-for-woocommerce#215]
Hello!

In the function kco_wc_prefill_consent() there is a check on whether the locale is 'de_DE' in which case German text will be outputted, and otherwise English. 

However, the locale 'de_DE_formal' (https://translate.wordpress.org/projects/wp/dev/de/formal/) can also be handled the same way as 'de_DE'.

**Comment by MichaelBengtsson** [comment]
@ahegyes This is in the current develop branch now. And we will release it with the next version. Sorry for the delay on this one.
