### ISSUE TITLE
Payment method not changed in Woo after first trying Vipps, then changing to Klarna

### ISSUE THREAD

**Issue by orjansteffensen** [krokedil/klarna-checkout-for-woocommerce#216]
_(PS! First posted on Vipps git: https://github.com/vippsas/vipps-woocommerce/issues/14)_

We have Klarna and Vipps as payment options. On some orders the customer starts payment via Vipps. The payment then fails, probably due to insufficient funds, the customer goes back and chooses to pay via Klarna. The order then goes through as it should.

The problem is that Vipps is still the registered payment method on the order data. So when we try to complete the order it prompts Vipps to capture the payment (which obviously fails) and we have to go in manually on the Woo order, change payment method to Klarna, before also logging into Klarna to activate the order there before being able to complete the order.

In the screenshot you can see the statuses of a customer who has done this. She started out with Vipps, but changed to Klarna after a failed payment via Vipps. The status bar does not catch this however.

![57071860-05f41d00-6cdc-11e9-989e-800ac1c23125](https://user-images.githubusercontent.com/24268072/58702661-ae160800-83a6-11e9-8fec-0d4fb17c1921.png)

**Comment by NiklasHogefjord** [comment]
Hi @orjansteffensen,
Could you please try the [Develop branch](https://github.com/krokedil/klarna-checkout-for-woocommerce/commits/develop) and see if that solves your problem?

We had a similar issue with another payment method. We now[ set KCO as the chosen payment](cb71f742f449172e9afb90f9a41868a98597f104) method right before finalizing the purchase in Woo.

**Comment by orjansteffensen** [comment]
Can confirm that the problem is solved with the develop branch. Should I just use that one for now then, or are there some other things that can break when using that?

**Comment by NiklasHogefjord** [comment]
Sorry for the late reply @orjansteffensen. You should be able to use the Develop branch. We aim to release a new version this week.

**Comment by orjansteffensen** [comment]
Great! Thanks for the reply.

man. 10. jun. 2019, 12:12 skrev Niklas Högefjord <notifications@github.com>:

**Comment by NiklasHogefjord** [comment]
Version 1.10.1 is now released and the problem should be fixed. Closing this issue.
