### ISSUE TITLE
Add support for payment method widget (if available for V3)

### ISSUE THREAD

**Issue by NiklasHogefjord** [krokedil/klarna-checkout-for-woocommerce#22]
I can't find it in the docs at the moment but if Klarna supports the Payment Method widget for v3 (like https://developers.klarna.com/en/se/kco-v2/payment-method-widget), then we should probably add support for it.

I would suggest adding it as a separate addon plugin since it probably should be available for both KP and KCO.

**Comment by kristibarbosky** [comment]
Klarna is building a pre-purchase product that will include upstream advertising (e.g. "as low as " messaging on a merchant product page).  This is not yet available in production or developers.klarna.com.
