### ISSUE TITLE
Minimize the number of request between Woo & Klarna during change in the checkout supporting Klarna Shipping Service [PI-2086]

### ISSUE THREAD

**Issue by NiklasHogefjord** [krokedil/klarna-checkout-for-woocommerce#234]

**Comment by NiklasHogefjord** [comment]
Currently if KSS is used, two updates/checkout freezes are triggered in the KCO iframe if a customer changes shipping method. Can we optimize this?

**Comment by Kurblin** [comment]
Hi @NiklasHogefjord, do you know the reason for this?

**Comment by NiklasHogefjord** [comment]
Hi @Kurblin,
This is happening to make sure that the shipping cost/information is correct displayed in WooCommerce. 

We are working on a rewrite of the KCO plugin at the moment. We will look into this more in detail next week to see if there is a possibility to remove the need of an extra update.

**Comment by kristibarbosky** [comment]
this work can't be done until updated made to Klarna code regarding JavaScript client events, so setting this to On Hold

**Comment by kristibarbosky** [comment]
Necessary data now hopefully available from Klarna in the event: https://developers.klarna.com/documentation/klarna-checkout/in-depth/client-side-events/#the-shipping-option-change-event

**Comment by kristibarbosky** [comment]
Closed with v2.4.1 release: https://github.com/krokedil/klarna-checkout-for-woocommerce/releases/tag/2.4.1
