### ISSUE TITLE
Shipping Methods is not generated in Klarna Checkout. 

### ISSUE THREAD

**Issue by onlyapproved** [krokedil/klarna-checkout-for-woocommerce#238]
We are experiencing since the latest release, or changes by Klarna, that the checkout is not requesting shipment methods in woocommerce. 

Even with standard Flat-Rate shipping added, the checkout is not quoting for shipment methods, but lets customers check out without paying for shipment.

**Comment by kristibarbosky** [comment]
@onlyapproved - I not able to recreate this problem in a test store yet, with shipping options in or outside the KCO iframe.  Could you please open a support case at support@krokedil.com and provide more details about your store configuration.
