### ISSUE TITLE
truncate all reference fields to 64 char

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#241]
Similar to https://github.com/krokedil/klarna-payments-for-woocommerce/issues/149, truncate all reference fields to 64 char (and have requested KCO to document this restriction in the API)
	
        	 error_code:	 BAD_VALUE	
          	 Bad value: order_lines[3].reference (size must be between 0 and 64)	
        	 Klarna-Correlation-Id:	 86149bcc-d1a8-4d6d-8fef-6564104f0518	
      	 timestamp:	 2019-09-01T14:06:04Z	

name:	 redacted	
            	 quantity:	 1	
            	 reference:	 1-abcd-wh240151-a19x8-5-5x112-et35-66-5-xf657-rs6-c6-style-montering	
            	 tax_rate:	 0	
            	 total_amount:	 99900	
            	 total_discount_amount:	 0	
            	 total_tax_amount:	 0	
            	 type:	 surcharge	
            	 unit_price:	 99900

**Comment by NiklasHogefjord** [comment]
Fixed in 5bb5019ab0ef5f04534f56c64c03584fcecf6268 & 21d21d0b210d30a46a30bd8e437ba041d908bf15
