### ISSUE TITLE
IE11 fails on URLSearchParams JavaScript function.

### ISSUE THREAD

**Issue by MichaelBengtsson** [krokedil/klarna-checkout-for-woocommerce#247]
https://github.com/krokedil/klarna-checkout-for-woocommerce/blob/develop/includes/class-klarna-checkout-for-woocommerce-confirmation.php#L161

**Comment by NiklasHogefjord** [comment]
Fixed in 5c4e6bda5df23e2d0c2b1b4724b9784de03b5b5b
