### ISSUE TITLE
Language issue in KCO

### ISSUE THREAD

**Issue by NiklasHogefjord** [krokedil/klarna-checkout-for-woocommerce#25]
Not sure why this is happening but even though I'm using English as the site language and Euro as the currency, the KCO checkout is displayed in Swedish. See an example here: http://recordit.co/eOxuu3MjjQ

**Comment by NiklasHogefjord** [comment]
@kristibarbosky After talking to Slobodan I understand that this is the preferred logic from klarnas side. Is that correct? If that's the case, might I ask why? :)

**Comment by kristibarbosky** [comment]
KP did not yet have English supported for all markets, but I believe that KCOv3 does support both market language & English for each market.  So it seems that KCO iframe should match the site language.  @slobodan - am I forgetting something?

**Comment by slobodan** [comment]
@kristibarbosky I believe that was the reason, yes.

**Comment by slobodan** [comment]
Fixed in `develop`. If the site has locale that starts with `en`, then purchase country sent to Klarna will be en-XX.

**Comment by kristibarbosky** [comment]
Test passed successfully,

1. Woo store using English as site language:
"order_id" : "50a7b3a3-bf6c-7284-862f-525aca5845da",
 "body" : {
      "purchase_country" : "SE",
      "purchase_currency" : "SEK",
      "locale" : "en-se"

![image](https://user-images.githubusercontent.com/15654455/36319457-f9aedfe2-1310-11e8-9de0-8c044e5a5239.png)

2. Woo store using Svenska as site language:
"order_id" : "736a04ca-abed-7fa8-ae3f-5cb55dc9d964",
 "body" : {
      "purchase_country" : "SE",
      "purchase_currency" : "SEK",
      "locale" : "sv-se"

![image](https://user-images.githubusercontent.com/15654455/36319493-16519c20-1311-11e8-9985-50f295eda821.png)

@slobodan - when will this fix be merged into master branch?  It seems likely that many merchants will want this.

**Comment by slobodan** [comment]
Great! I think we can push a new version early next week.
