### ISSUE TITLE
WPML multicurrency issue. Order in WooCommerce gets the default currency. Klarna gets the correct currency.

### ISSUE THREAD

**Issue by MichaelBengtsson** [krokedil/klarna-checkout-for-woocommerce#250]

**Comment by a-larsson** [comment]
This was a bug in WCML and should be resolved in the next version of WCML, a temporary fix is available in the support forum thread:
https://wpml.org/forums/topic/wpml-woocommerce-subscription-change-of-currency-after-checkout-completion/

Closing this issue
