### ISSUE TITLE
Does not work locally

### ISSUE THREAD

**Issue by forsvunnet** [krokedil/klarna-checkout-for-woocommerce#253]
A few versions ago the plugin stopped working on local websites (eg. http://kco-test.x). The KCO iframe is working on the checkout page, but no payments can be made. I'm just getting a generic error.

It means that we're no longer to test payments when we develop new websites, but have to create a staging website on a server in order to test if payments are working. It would be great if you could make the plugin work locally again.

**Comment by Pautomagi** [comment]
Im also receiving this generic error. But for me its happening locally (which can be walked around using the fix above) and on a staging or prod server. No other error messages except the Generic error `validation_service_failed` in the response from klarna api.

**Comment by MichaelBengtsson** [comment]
This is now fixed in version 2.0.0. We not longer require the validation callback to be triggered making you able to finish orders in a local test environment.
