### ISSUE TITLE
Not refereshing kco in mobile webview

### ISSUE THREAD

**Issue by muhammadarslan** [krokedil/klarna-checkout-for-woocommerce#254]
After placing an order with kco in webview mobile, it does not showup the kco form again, instead shows thank you for your order. Please check this out.

**Comment by MichaelBengtsson** [comment]
@muhammadarslan For support questions like this its recommended to send a ticket to support@krokedil.com.

Do you mean that when the customer finishes a purchase, and goes to place a 2nd purchase they still see the thank you iFrame from the old purchase they made?
