### ISSUE TITLE
Shipping option, required field not respected

### ISSUE THREAD

**Issue by carcarefreaks** [krokedil/klarna-checkout-for-woocommerce#256]
Hi,
We use a big danish shipping company called "shipmondo" earlier pakkelabels.dk
When using Klarna Checkout, the required shipping fields to select a drop point are not respected so a customer can checkout without selecting a drop point.

When this happens the order goes into status on-hold, and in worst case we do not ship the items = angry customers and lost money.

Do you have any ideas about how we can fix this?

Error: ”This order was made as a fallback due to an error in the checkout (Error message: Du skal vælge et udleveringssted, før du kan gå videre). Please verify the order with Klarna.”

**Comment by NiklasHogefjord** [comment]
Hi @carcarefreaks,
When looking at the Shipmondo for WooCommerce changelog it looks like they added support for the Klarna Checkout plugin in version 2.2.0. What version of the plugin are you using?

We are about to start a rewrite of how the checkout flow works with the Klarna Checkout for WooCommerce plugin (a tweak regarding when in the process the WooCommerce order is created). This rewrite will most likely solve the issue you're experiencing. I don't have an ETA for when this rewrite will be released but we will start working on it by the end of this month.

**Comment by carcarefreaks** [comment]
Hi @NiklasHogefjord 
We are on 3.0.4, so it should be supported from Shipmondo yes.
Will look forward to the rewrite, let me know if you need someone to test it when ready.
Our Klarna setup is currently disabled because of this issue.

Br,
Frederik

**Comment by jgangso** [comment]
Hi both,
I've been struggling with similar issue.
To me it seems like the validation for required fields is on place on the frontend JS. 
The `checkFormData` is also correctly triggered upon changes on input fields inside the `kco-extra-fields` section. 
However, inside `checkFormData`, the `validateRequiredFields` method is called only when `kco_wc.shippingUpdated` is true. That will be the case only when KCO iframe triggers the `shipping_address_change` event.

Out of curiosity I'm asking, wouldn't it solve the problem for the time being, if the `validateRequiredFields` method was triggered every time the `checkFormData` was called?

**Comment by jgangso** [comment]
Answering my own question, not out of the box at least. The validation would work, but the iframe stays in suspended mode with the "loading dots", which makes the user wait for them to disappear, instead of entering the missing data on the left hand side.

**Comment by carcarefreaks** [comment]
Hi,
Do we have any news regarding this subject?

**Comment by NiklasHogefjord** [comment]
Hi,

Sorry for the silence in this issue. We now have a rewrite of the plugin ready for beta testing: https://github.com/krokedil/klarna-checkout-for-woocommerce/tree/develop-v2.

This version has a changed checkout flow, when the order is created in Klarna vs when it's created in Woo. Hopefully this will make it more compatible with plugins like Shipmondo.

**OBS! It's recommended not to use this in production yet**. We are currently testing the plugin internally and will be better prepared after the christmas holidays.

**Comment by thegermin8er** [comment]
Hi,

I'm using Klarna Checkout for WooCommerce (1.11.7), WooCommerce Storefront Theme and WooCommerce Checkout Field Editor (1.5.26) with a custom required field. The validation works when I go to checkout the first time, but if I go to another page and come back (or refresh the page) the requirement is no longer respected and I can make the order without filling in anything in the required field. Also the red border around the required field is no longer working.

**Comment by MichaelBengtsson** [comment]
Hi @thegermin8er 

As Niklas wrote above, we have a fix for this with the next major update that we have. If you want you can download it in the link that Niklas provided in his comment above.

At this point however we feel that its fine to use this version in production as long as you keep an eye on it. And we are in the process of wrapping the development up and shipping it as the live version.
