### ISSUE TITLE
Add improved control in push_cb for orders with fraud_status "pending"

### ISSUE THREAD

**Issue by Kristian-Andersson** [krokedil/klarna-checkout-for-woocommerce#264]
When an order is made and gets the "fraud_status" = "pending", the order is set as "on-hold" in woocommerce meanwhile the order is reviewed by Klarna. 4 - 8h later Klarna sends a push to the store with the result on the order being either "Accepted" or "Rejected". In this push secuence we are currently not doing any control if the order in woo has "on-hold" status which in this case the wc order has.
https://github.com/krokedil/klarna-checkout-for-woocommerce/blob/dd9c97b777d29147ba41e844286cb99e52ddc356/includes/class-klarna-checkout-for-woocommerce-api-callbacks.php#L141

**Comment by Kristian-Andersson** [comment]
Solution to this would be to add a additional post meta to the orders that have fraud_status : Pending and then in the push_cb funcition (row 141), check if order has this post meta added to it.

**Comment by MichaelBengtsson** [comment]
Closed since this has been fixed in KOM instead.
https://github.com/krokedil/klarna-order-management-for-woocommerce/commit/0fee9882d30a37cc6759884d78b0ff3547265923
