### ISSUE TITLE
Allowed memory size exhausted on WooCommerce status page

### ISSUE THREAD

**Issue by kimmenbert** [krokedil/klarna-checkout-for-woocommerce#273]
It seems like your function to count how many orders in the last month that is created via API callback gets a bit too heavy when you have a large amount of orders.

2600 orders was too heavy, main issue being `get_post_meta( $order_id, '_created_via', true )` on all of those 2600 orders.

Ping me on slack if you need more info from me :)

**Comment by NiklasHogefjord** [comment]
Thanks for the report @kimmenbert. With the new rewrite of the KCO plugin I think this feature will be removed. I'll ping you on Slack for a followup :).

**Comment by MichaelBengtsson** [comment]
Closed by misstake. This will be resolved in the next version.

**Comment by MichaelBengtsson** [comment]
This has been fixed as of 2.0.1
