### ISSUE TITLE
Customer order comment is not saved

### ISSUE THREAD

**Issue by MMikael18** [krokedil/klarna-checkout-for-woocommerce#274]
My client's shop when you but comment in order and send it. In backend when I look order comment is not saved. 
There is all so error "This order was made as a fallback due to an error in the checkout (Error message: SyntaxError: Unexpected token < in JSON at position 0). Please verify the order with Klarna."

Is it possible that this is the reason why the comment is missing?

**Comment by MichaelBengtsson** [comment]
@MMikael18 Yes, if the order is created on a fallback we lose that type of information sadly. If you need support regarding this please email our support at support@krokedil.se

Since this is a support ticken i will be closing this issue.
