### ISSUE TITLE
germanized and kco >=2

### ISSUE THREAD

**Issue by andresendo** [krokedil/klarna-checkout-for-woocommerce#283]
Hello,
we are using germanized and the Klarna Checkout Plugin.

It works very well with:
```
/* Germanized Checkbox mit Klarna anzeigen  */
add_action( 'kco_wc_before_extra_fields', 'kco_wc_show_germanized_field' );

function kco_wc_show_germanized_field() {
    if ( class_exists( 'WooCommerce_Germanized' ) ) {
	$manager = WC_GZD_Legal_Checkbox_Manager::instance();
	$manager->render();
    }
}

```

But after the new 2.0 Update it don't work.. so now i try to change the position / hook position (to kco_wc_after_snippet).
The Checkout (the shipment checkbox) shows the checkboxes but one one checkbox is duplicated

<img width="1317" alt="Bildschirmfoto 2020-03-07 um 23 52 34" src="https://user-images.githubusercontent.com/255217/76153659-3b715000-60cf-11ea-8ed1-cde36b11b5ba.png">

**Comment by hannesdorn** [comment]
In koc 2.0.4 (released 2020.03.10) they added kco_wc_before_extra_fields again.
So the checkbox gets displayed. But I can't place an order since the checkbox gets not evaluated correctly.

**Comment by MichaelBengtsson** [comment]
@hannesdorn I do not have the same issue as you are doing when it comes to them not being validated correctly. Can you send a support ticket to support@krokedil.com and we can help you further there possibly?

**Comment by andresendo** [comment]
Hi, ok with the new update.. the checkboxes are back.. but i get one double checkbox..  comes this from koc or is this a germanized bug? But i don't have this on my system with the old koc plugin.

![Bildschirmfoto 2020-03-11 um 11 47 39](https://user-images.githubusercontent.com/255217/76423684-72818300-63a7-11ea-9725-648bbaa6b438.png)

**Comment by MichaelBengtsson** [comment]
@andresendo Im not sure why you are seeing the double of one checkbox. If you dont use the code that we provide in our gist, do you still see the one checkbox?

**Comment by andresendo** [comment]
@MichaelBengtsson without your code i don't see any checkbox

**Comment by MichaelBengtsson** [comment]
@andresendo Then i dont see this as an issue with our code but rather that the germanized plugin adds this checkbox twice for some reasson. Could you check with them regarding this?

**Comment by MichaelBengtsson** [comment]
I will be closing this issue since i believe this has now been resolved. If this is still an issue for you, please feel free to reopen the issue.
