### ISSUE TITLE
kco and WPC Bundle Plugin

### ISSUE THREAD

**Issue by andresendo** [krokedil/klarna-checkout-for-woocommerce#284]
Hi,
we are using the KCO and WPC Bundle Plugin.
We are disable the subarticles in all cart and checkout pages.. but the klarna checkout shows the subarticles.

We get this code for the old 1.11.7 kco plugin from the developer of wpc bundle.. 

```
if ( ! empty( $cart_item['woosb_parent_id'] ) ) {
			    continue;
			}
```

We added this in the class-klarna-checkout-for-woocommerce-order-lines.php after row 149... maybe you can add something like this in your plugin...?!

**Comment by andresendo** [comment]
Can you add this?

**Comment by andresendo** [comment]
For Version 2.0.12:

I added this on line 151 in the same class..

**Comment by a-larsson** [comment]
Hi @andresendo 

We tried this now with KCO 2.4.0 and it looks like this is working now together with WPC Bundle Plugin. So we will close this issue.
