### ISSUE TITLE
2.0.3 Major performance problem

### ISSUE THREAD

**Issue by shanemarsh28** [krokedil/klarna-checkout-for-woocommerce#285]
Have you been made aware of any database issues relating to 2.0.3?

We updated to this version late on Friday and we have suffered major server outages over the weekend which we today have traced to your latest release v2.0.3. It appears the changes have caused some sort of extensive DB write (maybe an out of control loop) and our two DB servers were pinned at 100% CPU for extended periods of time. 

This resolved itself when we rolled your plugin back to v2.0.2.

**Comment by kristibarbosky** [comment]
Hi @shanemarsh28 -
We're very sorry for the issue.  Could you please open a support ticket directly via support@krokedil.com for this?  Hundreds of merchants are running on this version without issues, but we certainly want to get this issue debugged and resolved.

**Comment by MichaelBengtsson** [comment]
Hi @shanemarsh28 

Its weird that changing from 2.0.3 to 2.0.2 would solve the issue. 2.0.3 was an incredibly small update that changed the name of an action and changed one variable. Nothing to do with the database. Are you sure it came from updating Klarna 2.0.3 and not something else happening during the same timespan?

**Comment by shanemarsh28** [comment]
Hi Michael, 

Thanks for coming back to me on this. We had a very large spamming attack which highlighted some bad SQL code in a custom plugin that pummeled the database with slow queries. I can confirm other factors were at play with this fault unrelated to your plugin and my initial diagnosis was wrong. I'm sorry for wasting your time. 

Shane
