### ISSUE TITLE
Custom shipping method field moved to kco-extra-fields when it should not

### ISSUE THREAD

**Issue by kimmenbert** [krokedil/klarna-checkout-for-woocommerce#287]
Hey!

We have created a custom field for a shipping method, hooking into `woocommerce_after_shipping_rate`

We have not enabled shipping methods inside of Klarna iframe, since that would not support having a custom field directly connected to the shipping method.

It seems like your moving of fields to kco-extra-fields also moves (duplicates) this field. Even if it's not needed.

## Pre KCO 2
![image](https://user-images.githubusercontent.com/4253817/76410904-0136d580-6391-11ea-9f76-1b581bc0e451.png)

## Post KCO 2
![image](https://user-images.githubusercontent.com/4253817/76410986-23c8ee80-6391-11ea-960f-fbdb1c23956e.png)

**Comment by NiklasHogefjord** [comment]
Hi @kimmenbert,

We will look into this. @MichaelBengtsson Perhaps it is just a matter of excluding fields that is added to the order review area from being moved?

**Comment by MichaelBengtsson** [comment]
Fixed in 0696be795777749da0ccd0354d70da1781c05f6e
