### ISSUE TITLE
Germanized Title compatiblity

### ISSUE THREAD

**Issue by andresendo** [krokedil/klarna-checkout-for-woocommerce#288]
Hi,
we are using germanized - germanized create two additional fields "billing_title" and "shipping_title".

It ty to add this to your plugin:

i added this to klarna-checkout-for-woocommerce.js line around 310:
```
	if( $('#billing_title').length ) {$("#billing_title option:contains(" + data.billing_address.title + ")").attr('selected', 'selected');}
			if( $('#shipping_title').length ) {$("#shipping_title option:contains(" + data.shipping_address.title + ")").attr('selected', 'selected');}
```
by the way - the is a console.log( data ); on line 307 - is this right??

and this to class-kco-gateway.php
billing_title & shipping_title to the $standard_woo_checkout_fields array

I don't if this is enough - but in this moment i think its work ...

Is it possible that you add this to your plugin???

**Comment by MichaelBengtsson** [comment]
Hi @andresendo 

From what i can tell it looks like this code should work. We will look into this and see if we can add it into the plugin in a way that does not cause any issues.

**Comment by andresendo** [comment]
Can you add this? so i can update this plugin ;)

**Comment by andresendo** [comment]
For Version 2.0.12:

I added this after setCustomerData in klaran-checkout-for-woocommerce.min.js

```
 if( a('#billing_title').length ) {a("#billing_title option:contains(" + e.billing_address.title + ")").attr('selected', 'selected');}
	         if( a('#shipping_title').length ) {a("#shipping_title option:contains(" + e.shipping_address.title + ")").attr('selected', 'selected');}
```

And and added `'billing_title', 'shipping_title',` to the $standard_woo_checkout_fields array in class-kco-gateway.php

**Comment by muntjaber** [comment]
I am closing this since we've moved feature request to our roadmap. You can find this request [here](https://krokedil.upvoty.com/b/klarna-checkout-for-woocommerce/compatibility-germanized-title/).
