### ISSUE TITLE
Support for Order Pay Page

### ISSUE THREAD

**Issue by syntaxerror** [krokedil/klarna-checkout-for-woocommerce#289]
When using plugins like WooCommerce Order Proposal there is no support for Klarna Checkout.
The developer of this plugins tells us the following:
> We are using the Woocommerce Pay Page for predefined orders.
> It is the only way to pay for orders that have a preset/custom price in Woocommerce.
> Unfortunately some payment plugins seem not to support it.
> The only way to make it work is to contact the payment plugin author and ask him to add the Order Pay Page.

What's your opinion to this? Is this info correct, and if so, would you please consider adding the needed support for it?

**Comment by MichaelBengtsson** [comment]
Hi @syntaxerror.

We can look into this, but im not sure at what point we will have the opportunity to do so. But if you could send us a support ticket at support@krokedil.com and potentially send us the plugin in question as well, then we can take a look at it for sure.

**Comment by syntaxerror** [comment]
Not so easy just sending you the plugin obviously. :)
> This message was created automatically by mail delivery software.
> 
> A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:
> 
>   support@krokedil.com
>    host aspmx.l.google.com [173.194.73.27]
>    SMTP error from remote mail server after end of data:
>    552-5.7.0 This message was blocked because its content presents a potential
>    552-5.7.0 security issue. Please visit
>    552-5.7.0  https://support.google.com/mail/?p=BlockedMessage to review our
>    552 5.7.0 message content and attachment content guidelines. h8si3528276ljj.32 - gsmtp

**Comment by MichaelBengtsson** [comment]
@syntaxerror We now have a working branch that will support the normal WooCommerce pay for order flow. And we are hoping that this will work with the plugin that you sent us. I will test with that closer to release as well to make sure

**Comment by syntaxerror** [comment]
Thanks for the update, it sounds good. :)

**Comment by muntjaber** [comment]
I am closing this since support for pay for order was added [in version 2.6.0](https://github.com/krokedil/klarna-checkout-for-woocommerce/releases/tag/2.6.0)
