### ISSUE TITLE
Klarna selected as default payment method after 1st buy

### ISSUE THREAD

**Issue by carcarefreaks** [krokedil/klarna-checkout-for-woocommerce#290]
Hi,
Is there a way to prevent Klarna to be default payment method for the customer after first purchase?

Now when you have used klarna once it always goes direct to klarna, instead of letting the customer choose payment method. It blocks for our upsales and for using giftcards etc.

**Comment by NiklasHogefjord** [comment]
Hi,
This is how WooCommerce works and there is no way to change this via the Klarna plugin settings. However, WooCommerce probably offer some filter to override/change the default payment method. I would suggest you look into _woocommerce_available_payment_gateways_.

The actual problem you seem to have now is that you are not able to see Upsell offers and fields for giftcards. What plugins do you use for this features?

**Comment by MichaelBengtsson** [comment]
Closed since there has not been a reply in a long time. If you need further help please contact our support at support@krokedil.com
