### ISSUE TITLE
Indicate Klarna environment (test vs. live) on Woo order [PI-1521]

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#296]
Currently a Woo admin could check this at the '_wc_klarna_environment' meta field (using the 'Show Hidden Post Meta' plugin), but to make it easier for merchants, as time permits, could you please enhance the code to indicate the Klarna environment (test/playground vs. live/production) in the Woo order?  thx!

(Created same request for KP: https://github.com/krokedil/klarna-payments-for-woocommerce/issues/180)

(Should also consider KIS orders)

**Comment by MichaelBengtsson** [comment]
Solved in https://github.com/krokedil/klarna-order-management-for-woocommerce/commit/daa7c2fd8971a8bdad0af39038193bde83ae4e67

**Comment by kristibarbosky** [comment]
thank you for this enhancement! 
![image](https://user-images.githubusercontent.com/15654455/87172078-a9a66900-c2a1-11ea-8928-9edb898bee01.png)
