### ISSUE TITLE
checkout for wordpress 5.4 not working

### ISSUE THREAD

**Issue by jay98273498237** [krokedil/klarna-checkout-for-woocommerce#301]
The callback function done by Klarna back to the shop after successful purchase doesn't update the order status any more.
System was upgraded to wordpress 5.4 and woocommerce 4.0.1

**Comment by jay98273498237** [comment]
Seems to be fixed by Klarna or someone now

**Comment by kristibarbosky** [comment]
https://status.klarna.com/incidents/jtfw6rt5mq1h

**Comment by MichaelBengtsson** [comment]
I will be closing this since it seems like the issue has been resolved. If not then please reopen the issue.
