### ISSUE TITLE
Checkbox Issue with Germanized

### ISSUE THREAD

**Issue by andresendo** [krokedil/klarna-checkout-for-woocommerce#308]
Hi,
I know there are always problems with Klarna and germanized. Now I have a strange problem. If you order in the shop for the first time and then logon with email + postal code, the message "please accept ....." appears. In the next step the user click this checkbox - but klarna waits and waits and waits. 
i hope you can understand my problem... i already discuss this with germanized but he think its a klarna checkout problem. 

<img width="1643" alt="admin-ajax" src="https://user-images.githubusercontent.com/255217/80010268-79cd9d80-84ca-11ea-816b-fd6a2eb9cfe1.png">

**Comment by MichaelBengtsson** [comment]
Hi @andresendo.

Sorry for the late response, but what version of Klarna Checkout are you using when you get this error? With the latest version this should not be an issue.

**Comment by MichaelBengtsson** [comment]
Since we have not gotten any response on this i will close this issue. This works for us, but if you are still having issues feel free to reopen this.
