### ISSUE TITLE
Wrap KCO errors with a filter to enable merchant customization of error messages

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#317]
Relating to https://wordpress.org/support/topic/ability-to-catch-common-errors-from-klarna-checkout/#post-12925488, please update KCO plugin to enable a merchant to customize the errors returned from KCO and instead display more customer friendly error messages.

**Comment by MichaelBengtsson** [comment]
Sadly we will not be implementing this. Since we do not want to manipulate the error messages that are returned by Klarna to our plugin.
