### ISSUE TITLE
2.0.15 breaks integrated Vipps-payment

### ISSUE THREAD

**Issue by orjansteffensen** [krokedil/klarna-checkout-for-woocommerce#322]
Seems the latest release breaks functionality for Vipps integrated in KCO iframe.

If you pick Vipps as payment option you're sent to /wp-login.php after this update.

Screen recording can be seen here: https://photos.app.goo.gl/WUxYuv7y34njCUn18
Bad quality, but it shows the problem.

**Comment by NiklasHogefjord** [comment]
Hi @orjansteffensen,
Can you test this branch and see it solves your problem: https://github.com/krokedil/klarna-checkout-for-woocommerce/tree/develop-redirect-for-epm

**Comment by orjansteffensen** [comment]
Yes, that one seems to solve it. Will it be included in 2.0.16 by any chance?

**Comment by NiklasHogefjord** [comment]
Yes, it will be included in 2.0.16.

**Comment by anbohm** [comment]
When will 2.0.16 be released?

**Comment by NiklasHogefjord** [comment]
@anbohm this week, probably June 22 or 23.

**Comment by NiklasHogefjord** [comment]
Merged into Develop now.

**Comment by kristibarbosky** [comment]
2.0.16 was released 2020 June 23: https://github.com/krokedil/klarna-checkout-for-woocommerce/releases/tag/2.0.16

Latest release available at: https://github.com/krokedil/klarna-checkout-for-woocommerce/releases
