### ISSUE TITLE
READ_ONLY_ORDER error

### ISSUE THREAD

**Issue by raindeer** [krokedil/klarna-checkout-for-woocommerce#325]
Since updating to 2.0.15 we once in a while see failing payments with READ_ONLY_ORDER errors. Never saw this in previous version.

Any idea why?

Post 403:
order_id: xx
correlation_id: xx
request_timestamp: 2020-06-12, 04:24
action: Update order
merchant_id: xxx
request_path: api/merchant/xxx/v3/orders/xxx
caller_ip: xxx
error_code: READ_ONLY_ORDER
error_messages: Resource is read-only

**Comment by kristibarbosky** [comment]
This can happen for multiple reasons, e.g.
https://wordpress.org/support/topic/error_coderead_only_order/
https://wordpress.org/support/topic/error-code-read-only/

If further support is needed debugging, for direct support you can open a support case via support@krokedil.com
