### ISSUE TITLE
Handle [optional] stock reservations for KCO orders

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#34]
While the validate calls is used to verify stock prior to placing a KCO order, for a high velocity store, stock may still be reduced to 0 after the validate call but prior to the order being placed, particularly possible for iDeal NL orders that have an extra step where customers enter data after clicking the Place Order button in the KCO iframe.  Therefore it is currently possible for the KCO order to be placed in Klarna but rejected in Woo with an out of stock error.

To resolve this, can we hook into existing Woo stock reservation plugins?  or must we build in custom stock reservation?

**Comment by slobodan** [comment]
@kristibarbosky would suggesting them to use something like this be an option?

https://github.com/jamesgol/woocommerce-cart-stock-reducer

**Comment by kristibarbosky** [comment]
@slobodan - yes, this could be a good option, but might still need some work.  When I set my stock=1 and try to check out, I get a validate error: https://wp-kco.mageklarna.com/cart/?stock_validate_failed
