### ISSUE TITLE
Hide shipping address/method if only virtual products are in cart

### ISSUE THREAD

**Issue by lzudemz** [krokedil/klarna-checkout-for-woocommerce#341]
Hello,

I plan on switching to Klarna Checkout but have a little problem.

I'm selling virtual products along with non-virtual products in my store. For example a virtual gift card for my store and products like posters that are shipped.

I saw that when I placed a virtual product into my cart the Klarna Checkout displayed a shipping option. This would be very confusing for the customer if he only purchases a virtual product and suddenly sees a shipping method. The shipping method is only shown in the Klarna Checkout and not in WooCommerce when I switch off the Klarna Checkout. 

Is there any way for the Klarna Checkout to check if the cart only contains a virtual product and then hide the Shipping Method?

This would be really awesome!

Best regards,
Lukas

**Comment by NiklasHogefjord** [comment]
Sorry for the late reply @lzudemz. This sounds like a more general support question. If you still need input regarding this please get in touch with our support at support@krokedil.com.
