### ISSUE TITLE
Merchants doesn't see where they should add Mid and Secret

### ISSUE THREAD

**Issue by NiklasHogefjord** [krokedil/klarna-checkout-for-woocommerce#35]
I've got several support tickets from merchants that doesn't take the time to read through the documentation and don't know where to enter _Username_ and _Password_. They don't notice that the flags are clickable. 

I have added a screenshot in the docs page here https://docs.woocommerce.com/document/klarna-checkout/#section-4, but I think we should make it easier for the merchant to notice this section. 

Here are a few suggestions on what could be done:

- EU/US section could be displayed higher up on the settings page.
- Depending on the store base country one of the two (EU/US) could be expanded by default.
- Making the UX more intuitive that EU/US is expandable and that the merchant needs to enter data in one of the two areas.

Any thoughts from you guys on this?

**Comment by kristibarbosky** [comment]
Good feedback - I agree with all 3 suggestions.
