### ISSUE TITLE
purchase_country issue

### ISSUE THREAD

**Issue by krambriw** [krokedil/klarna-checkout-for-woocommerce#351]
Hello, using Woo with KCO since long, working great for Swedish customers. But customers in Norway does not see the Norwegian version of KCO and cannot therefore finish the purchase. Everything looks fine, correct currency NOK, customer can enter all relevant details like address in Norway, personal id, phone number, everything is correctly handled but for some reason, KCO still believes customer is in Sweden and therefore shows the Swedish KCO version. And yes, we have agreement with Klarna in place for Norway 
According to technical support, most likely wrong purchase_country is taken from Woo. _But where can I set that? I have configured that the customers purchase place should be "located" (I assume this is then supposed to happen automatically)_
I think you may have changed something in a KCO update since I know it has worked before, I do have some older orders from Norway in the system. Unfortunately there are no such old log files left that I can check
Best regards, Walter

**Comment by NiklasHogefjord** [comment]
Hi Walter,

Sorry for the late reply. Here is how the logic for _purchase_country_ is handled: https://github.com/krokedil/klarna-checkout-for-woocommerce/blob/3adeda6b26c7f74adc0fdad8ffea4de77553425a/classes/requests/class-kco-request.php#L103

Basically the plugin is trying to get the country from _WC()->customer->get_billing_country()_. If that isn't set we grab the country from _ wc_get_base_location()_.

If you cant solve the issue I suggest that you send us an email to support@krokedil.com and we will try to help you further.
