### ISSUE TITLE
KCO changes from 2.016 to 2.1.0 destroys shipping slip creation in Germanized plugin

### ISSUE THREAD

**Issue by mnmedia** [krokedil/klarna-checkout-for-woocommerce#357]
Hi Krokedil team,

We use Germanized PRO plugin as a means to make sure, woocommerce is legally 100% in line with German law. Therefore, the plugin is essential. Update of KCO from 2.0.16 to 2.1.0 and above crashes a functionality of Germanized PRO: automatic creation of shipping slips (which for us is essential since that triggers sending the shipping slip to the fulfilment partner).

I have thoroughly tested the situation with several KCO versions in my staging environment. The issue is present from 2.1.0 onwards. No specific errors are logged with systemwide debugging log and KCO logging on.

To me, it simply seems that a standard woo hook might have been disabled from 2.1.0 onwards that is used by Germanized PRO to trigger the creation of the PDF.

Germanized PRO uses its own shipment system, however it has been fully functional up to KCO 2.0.16 ... Only the creation of the PDF is somehow blocked in 2.1.0 onwards - everything else is working fine.

Could you please check for the cause within the code changes of KCO from 2.0.16 to 2.1.0 and reverse or solve it in your next version.

This is an urgent problem for us, since we prefer NOT to run on our live site older KCO versions for security reasons ....

Thank you for your efforts.
Best
Michael

**Comment by mnmedia** [comment]
This issue is still present in KCO 2.3.1 - Rolling back to KCO 2.0.16 instantly resolves the issue .... which means we still have to run KCO 2.0.16 to get proper automation. May I ask you again to please look into this issue, so that we're not risking security issues in the future by getting stuck on KCO 2.0.16.

The developer of Germanized Pro is aware of the issue and also looking into it but could not localize the issue since it is not related to any code changes in  Germanized Pro, but changes by KCO ...

**Comment by mnmedia** [comment]
Here is an interesting experiment I did: In my sandbox, I used KCO 2.1.0 (the first version creating the issue) and simply replaced its klarna-checkout-for-woocommerce.php version using the KCO 2.0.16 klarna-checkout-for-woocommerce.php ...

Guess what ... Germanized Pro correctly produced the shipping slip. So, it seems, the issue can be boild down to one of the few changes from KCO 2.0.16 to KCO 2.1.0. Which are basically occuring in the following lines (referenced to 2.0.16 klarna-checkout-for-woocommerce.php):

147 onwards:
![grafik](https://user-images.githubusercontent.com/45258802/95314198-496b9700-0891-11eb-84cd-61b9e84d43e9.png)

219 onwards:
![grafik](https://user-images.githubusercontent.com/45258802/95314264-5be5d080-0891-11eb-8496-caf2e6054b8d.png)

328 onwards (biggest change ... lots of code dismissed in 2.1.0)
![grafik](https://user-images.githubusercontent.com/45258802/95314414-8fc0f600-0891-11eb-9fe2-17793e9db5c8.png)
![grafik](https://user-images.githubusercontent.com/45258802/95314474-a23b2f80-0891-11eb-88a1-cb08ec082cb2.png)
![grafik](https://user-images.githubusercontent.com/45258802/95314504-ad8e5b00-0891-11eb-955f-24d7fb3ed593.png)

One of these changes definitely creates the issue. Its not created by changes in other php files ...

The developer of Germanized Pro (Vendidero) looked into their side of the issue and did not find anything that was deviating from Woo specifications in their code. As my experiment clearly showed, the issue is created by KCO, even if it affects Germanized Pro.

Pleas look into this issue. since both plugins are essential for a good number of German Woo shops ...

Thank you.
Best
Michael

**Comment by mnmedia** [comment]
Ok, I further boild it down to the ONE line that creates the issue. It works in KCO 2.1.0 as well as in KCO 2.3.1 ...

Removing line 204 (in 2.3.1):
`204			include_once KCO_WC_PLUGIN_PATH . '/classes/class-kco-confirmation.php';`

Now the issue in Germanized Pro is GONE and everything in KCO/Woo seems to work just fine: orders are created. eMails sent and most importantly the order is added to the Klarna system (playground in test mode).

Thus, the issue is created by 
/classes/class-kco-confirmation.php

This file mainly contains the code that has been part of 2.0.16 klarna-checkout-for-woocommerce.php line 328 onwards:

![grafik](https://user-images.githubusercontent.com/45258802/95319056-b124e080-0897-11eb-942a-a74a6c178b8c.png)
![grafik](https://user-images.githubusercontent.com/45258802/95319139-ce59af00-0897-11eb-9594-98c58a98a1d7.png)
![grafik](https://user-images.githubusercontent.com/45258802/95319169-d74a8080-0897-11eb-998e-4b02000c04e7.png)

Now that the issue is boiled down, probably you'll be able to fix it.

**Comment by MichaelBengtsson** [comment]
We have found a solution for this along with @mnmedia in a support ticket. The issue here is that we need to up the priority of the action that triggers the order confirmation on our side. We will have this solved with the next release of the plugin.
