### ISSUE TITLE
After saving Klarna Checkout settings, you get an error that test mode is enabled

### ISSUE THREAD

**Issue by darylstone** [krokedil/klarna-checkout-for-woocommerce#360]
Hello,

I have tested it on two different websites, both on different hosting providers, after saving the changes in klarna chekout you get the warning: It looks like you have test mode active but no test credentials added. Please either turn off test mode or add test credentials.

However, both sites are using klarna since about a year. So purchases have been made many. I think that it might happen with the recent version of klarna checkout plugin. 

Klarna Version: Version 2.3.1 | Krokedil 
Latest Wordpress & Woocommerce Version
API CREDITENTIALS USED ONLY FOR PRODUCTION UNDER EUROPE

**Comment by kristibarbosky** [comment]
Hi @darylstone  -
This error can be displayed incorrectly sometimes, and if test mode is not active, this error can be ignored.  It does not affect accepting purchases in the store.

This should be fixed in the next KCO release, possibly this week.

(Related: PI-2041 , drw36w)

**Comment by MichaelBengtsson** [comment]
Hi @darylstone 

Yes this is an issue in the latest versions of the plugin. There will be a new version out this week that solves the issue. The current target for the release is Wednesday this week, 21/10-2020. But for the error message, it does not actually do anything. It just notifies the merchant that they might be an issue. It can be ignored and the plugin safely used.
