### ISSUE TITLE
Improve 405 error messaging when Klarna credentials are incorrectly configured

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#37]
Merchants are encountering issues when their Klarna credentials are a valid username & password, but aren't correctly configured for the market they are using them for, e.g. 'correlation_id' => 'd420749c-3cd0-442a-9e02-24b03c10975d',

	 message:	 Bad request with status 405 	
  	 thread:	 dw-41 - GET /api/merchant/*****/v3/orders/	
  	 timestamp:	 2018-04-09T11:17:22.431Z	

4/9/187:17:22.431 AM | {	[-]	  	exception:	javax.ws.rs.NotAllowedException: HTTP 405 Method Not Allowed

While the resolution for this issue is for the Klarna credentials to be correctly configured, it would be a nice enhancement for the Woo plugin to provide a nicer error message to help merchants better in this scenario.

**Comment by NiklasHogefjord** [comment]
@kristibarbosky Can a 405 response happen for other issues as well or would it be ok to add an error message saying something like "Your account needs to be controlled/checked by Klarna"?

**Comment by kristibarbosky** [comment]
@NiklasHogefjord - While I can't guarantee that this error is only thrown in this case, since the HTTP 405 code is specifically for "Method not allowed" per below, I think it is fair to shown a generic error such as "HTTP 405 error: this Klarna API method call is not allowed.  Please work with Klarna to configure the credentials to allow this method call."

[405 METHOD NOT ALLOWED](https://httpstatuses.com/405)
The method received in the request-line is known by the origin server but not supported by the target resource.

**Comment by NiklasHogefjord** [comment]
Thanks @kristibarbosky, we'll change it to that!

**Comment by kristibarbosky** [comment]
I recreated this and while you don't get the 405 in the response body, it should be in the status code in the HTTP headers.  Can you pull it from there?


4/10/188:52:28.000 AM | 24.123.234.155 - K500493 [10/Apr/2018:12:52:28 +0000] "GET /checkout/v3/orders/ HTTP/1.1" **405** 167 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36" "24.123.234.155" 0.003 "848b2a55-5c27-4337-b4d4-c2faaa91a83c"
-- | --




![image](https://user-images.githubusercontent.com/15654455/38557950-af1456b4-3c9c-11e8-9fe4-ff4a544185cc.png)

**Comment by kristibarbosky** [comment]
@MichaelBengtsson - I tested this (using K500493) on my KCO test store, but I still don't see any error in the storefront.  I do see an error in the logs, but still not very helpful.  I was hoping to see something like "HTTP 405 error: this Klarna API method call is not allowed. Please work with Klarna to configure the credentials to allow this method call."

![image](https://user-images.githubusercontent.com/15654455/38885428-dcbac3b0-4240-11e8-8151-e712811123bd.png)

	uid: d4cd7ec3-56df-42db-8244-d3098cda7da5

**Comment by NiklasHogefjord** [comment]
I can't find the exact commit where we solved this now, but it should be taken care of. Currently the customer is now being directed to the cart page and the following message is displayed:
![image](https://user-images.githubusercontent.com/985946/51893641-cbf64080-23a5-11e9-90ce-9b23b6adea9c.png)

Is that ok or should it be a more detailed description of the problem?

**Comment by MichaelBengtsson** [comment]
Closed for now since this seems to be resolved. If not then just reopen this @kristibarbosky
