### ISSUE TITLE
Hook for when payment fails.

### ISSUE THREAD

**Issue by Preen** [krokedil/klarna-checkout-for-woocommerce#372]
### Description of the issue
Not able to capture event when payment fails and popup with is visible
"Vi kunde tyvärr inte godkänna detta köp.
Vår betalleverantör Klarna kan inte godkänna detta köp för tillfället. Vänligen välj ett annat betalsätt."

### Expected behavior
Have a hook that we can use in order to present additional content such as invoicing option.

### Actual behavior
Can only capture events before the actual payment fails. Have tried with these hooks.
'wc_klarna_push_cb'
'kco_wc_confirm_klarna_order'
'kco_wc_process_payment'
'woocommerce_order_status_pending'

### Steps to reproduce the behavior
Pay with a failing test account

### Klarna plugin version
latest

### WordPress version
latest

### WooCommerce version
latest

### Before submitting
Make sure to try the following steps before you submit the issue
* Update the plugin to the latest version and test again.
* Test with the [Storefront](https://wordpress.org/themes/storefront/) theme.
* Deactivate any other plugin except WooCommerce and Klarna Checkout for WooCommerce and test again.

**Comment by NiklasHogefjord** [comment]
Hi @Preen,
Sadly we don't get any information from Klarna when this happens (neither in backend or frontend). The information is mainly to inform the customer that the selected payment method is not accepted by Klarna.

I actually think your request is a good idea, however, this is not something that Klarna have any plans to add support for at the moment.

**Comment by Preen** [comment]
Hey, have there been any changes in the above request? :)

**Comment by NiklasHogefjord** [comment]
No changes. Sorry.
