### ISSUE TITLE
Magic Method Needs Public Visibility

### ISSUE THREAD

**Issue by Tro95** [krokedil/klarna-checkout-for-woocommerce#373]
### Description of the issue
This plugin sets the magic method `__wakeup()` to private visibility in https://github.com/krokedil/klarna-checkout-for-woocommerce/blob/b59b234c217268b1df9ff2530f43a8051af5401c/klarna-checkout-for-woocommerce.php#L129, however magic methods **must** be declared as public as stated in https://www.php.net/manual/en/language.oop5.magic.php.

Using PHP 8.0, the following warning is generated:
```
PHP Warning:  The magic method KCO::__wakeup() must have public visibility in /var/www/wordpress/wp-content/plugins/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce.php on line 129
Warning: The magic method KCO::__wakeup() must have public visibility in /var/www/wordpress/wp-content/plugins/klarna-checkout-for-woocommerce/klarna-checkout-for-woocommerce.php on line 129
```

### Expected behavior
When using PHP 8.0, no warning is generated.

### Actual behavior
When using PHP 8.0, a warning is generated.

### Steps to reproduce the behavior
Using the PHP 8.0 CLI:
```bash
$ php -v
PHP 8.0.0 (cli) (built: Nov 27 2020 12:26:05) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.0, Copyright (c), by Zend Technologies
```
and the Wordpress CLI tool available from https://wp-cli.org/

Running `wp` in the CLI generates the warning.

### Klarna plugin version
2.4.1

### WordPress version
5.6

### WooCommerce version
4.8.0

### Screenshots
N/A

### Before submitting
Make sure to try the following steps before you submit the issue
* Update the plugin to the latest version and test again.
* Test with the [Storefront](https://wordpress.org/themes/storefront/) theme.
* Deactivate any other plugin except WooCommerce and Klarna Checkout for WooCommerce and test again.

**Comment by MichaelBengtsson** [comment]
Hi @Tro95.

This will be fixed for the next version of the plugin. This should however not effect anything, since its just a warning. But we will make sure the warning is not created.
