### ISSUE TITLE
Wrong currency is displayed before the billing address is submitted

### ISSUE THREAD

**Issue by raindeer** [krokedil/klarna-checkout-for-woocommerce#377]
### Description of the issue
The cart is displayed in the wrong currency before the billing address is inputed.

### Expected behavior
The same currency shall be used in the checkout page cart as on the product page (based on geolocation)

### Actual behavior
The cart refreshes when the checkout page is loaded and the default currency is displayed.

### Steps to reproduce the behavior
Use Woocommerce multilingual and specify different currencies for different countries based on geolocation.
Add a product to the cart and go to the checkout page. Before the billing address has been filled in, the currency is the default currency (not the one based on the geo location). When the billing address is inputed the cart is refreshed and the currency is correct again.

The error can be seen here: https://flowneuroscience.com/product/flow-device/ if you are in Sweden, Denmark or UK.
Add the product to the cart and go to checkout. First SEK (if in Sweden) is displayed correctly, then the cart is refreshed and Euro is display. See screenshot.

### Klarna plugin version
2.4.2

### WordPress version
5.3.6

### WooCommerce version
Woocommerce 4.7.1
Woocommerce multilingual 4.10.4

### Screenshots
<img width="1161" alt="Screenshot 2021-01-29 at 12 58 23" src="https://user-images.githubusercontent.com/288633/106272679-b7b5da00-6231-11eb-960e-5e29a1d42d75.png">

**Comment by a-larsson** [comment]
Hi @raindeer 

When I try to re-create this on your site I do not get the  fault you are showing.

I land on the product page and there I see the pound price and english text. When I add the product to the cart and go to the checkout I see the prices in SEK as it should be.

I believe this might be more of a configuration issue as I can not recreate this issue myself

Best regards
Andreas

**Comment by NiklasHogefjord** [comment]
Closing this issue now. If the problem remains, please get in touch with us via support@krokedil.com
