### ISSUE TITLE
Infinite confirm loading in Test mode

### ISSUE THREAD

**Issue by pfasang** [krokedil/klarna-checkout-for-woocommerce#383]
### Description of the issue
After clicking on confirmation button, modal appears and page is stuck on this step. In Safari and Firefox test mode works fine, modal appears and after that I see redirect to "order-received" page. 
There are no errors displayed in console. 

### Expected behavior
Redirect user from checkout to "order-received" page

### Actual behavior
Loading modal opens and no redirection is provided. 

### Steps to reproduce the behavior
1, Open the checkout page
2, Fill klarna fields
3, Click on confirm order button "Place order"

### Klarna plugin version
2.5.1

### WordPress version
5.6

### WooCommerce version
5.1.0

**Comment by MichaelBengtsson** [comment]
Hi @pfasang Did this start happening with the latest version of the plugin or was this the first version you tested?

Would it be possible for you to take a recording of the screen along with the browser console open for me to take a look at?

**Comment by pfasang** [comment]
No, I noticed it in 2.4.3 and same behaviour appears in Safari until I updated to 2.5.1.
I cannot send you screen record, but here is ss:
![Screenshot 2021-03-31 at 18 03 47](https://user-images.githubusercontent.com/25959727/113200567-c425d580-9268-11eb-9dff-b906d2416938.png)

It stops at **require-client-validation-response** script, before wc ajax update script

**Comment by pfasang** [comment]
Hi @MichaelBengtsson there are no errors in console and cart is empty from different reason

**Comment by pfasang** [comment]
We figure it out. Issue was caused by Vue and postscribe.
