### ISSUE TITLE
KCOv3 order line data doesn't reflect original price, only discounted price

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#39]
When a merchant has a product that is sold at a reduced price (no discount code needed), Klarna is only receiving the discounted price, not the original price

For example, for this product: 
https://tights-no.nhgdev.xyz/butikk/skins-a400-nexus/?attribute_pa_storrelse=s
Klarna is sent 82500 (the discounted price), but never 149900 (the original price):

   "order_lines" : [ {
        "reference" : "skins-a400-nexus-1",
        "name" : "Skins A400 Womens Nexus Long Tights - S",
        "quantity" : 1,
        "unit_price" : 82500,
        "tax_rate" : 2500,
        "total_amount" : 82500,
        "total_tax_amount" : 16500,
        "total_discount_amount" : 0,
        "product_url" : "https://tights-no.nhgdev.xyz/butikk/skins-a400-nexus/?attribute_pa_storrelse=s",
        "image_url" : "https://tights-no.nhgdev.xyz/wp-content/uploads/sites/7/2017/06/W2A0185-70x86.jpg"
      }

If Klarna is sent the original price (and discounted price) to still reflect the correct order total data, then the customer can see the discounted price in Klarna data (app, invoice, etc.)

**Comment by kristibarbosky** [comment]
relates to Klarna internal issue: https://jira.int.klarna.net/jira/browse/PI-268

**Comment by MichaelBengtsson** [comment]
There is a fix for this in the current develop branch of the plugin.

**Comment by kristibarbosky** [comment]
@MichaelBengtsson - When I tested (with store based in Germany) with taxes exclusive of price, I got an error with order totals not matching:

Order needs manual review, WooCommerce total and Klarna total do not match. Klarna order total: 9580. Order status changed from Processing to On hold.

added on April 17, 2018 at 5:48 pm Delete note

Order created via Klarna Checkout API Callback. Please verify the order in Klarnas system. Klarna order ID: dcb1c89d-bc61-7565-89b8-98a2c77976b2.

When I tested with prices inclusive of tax, I got a BAD_VALUE error:

 "error_messages" : [ "Bad value: total_amount" ],
      "correlation_id" : "450e8952-e1eb-4c99-b631-163a21025742"

  "order_amount" : 8050,
      "order_tax_amount" : 0,
      "order_lines" : [ {
        "reference" : "6162311",
        "name" : "Party Cats",
        "quantity" : 4,
        "unit_price" : 2013,
        "tax_rate" : 0,
        "total_amount" : 8050,
        "total_tax_amount" : 0,
        "total_discount_amount" : 420,
        "product_url" : "https://wp-kco.mageklarna.com/product/party-cats/",
        "image_url" : "https://wp-kco.mageklarna.com/wp-content/uploads/2017/12/hqdefault-100x100.jpg"
      }, {
        "type" : "shipping_fee",
        "reference" : "free_shipping:15",
        "name" : "Free shipping",
        "quantity" : 1,
        "unit_price" : 0,
        "tax_rate" : 0,
        "total_amount" : 0,
        "total_tax_amount" : 0
      } ]

**Comment by MichaelBengtsson** [comment]
Closing this since after talking with Klarna and reviewing this we dont think that we can realistically support this.

**Comment by kristibarbosky** [comment]
This is now documented at: https://docs.krokedil.com/article/287-klarna-checkout-faq#h-H2_13
