### ISSUE TITLE
No shipping for customers, if `#ship-to-different-address-checkbox` is missing from template `checkout/form-shipping.php`

### ISSUE THREAD

**Issue by adevade** [krokedil/klarna-checkout-for-woocommerce#397]
### Description of the issue
I have a theme where the WooCommerce template `checkout/form-shipping.php` has been modified. It is missing the input checkbox `#ship-to-different-address-checkbox`.
When a customer that is not logged in fills in their address in Klarna Checkout, no shipping zone is ever matched if this checkbox is missing.

### Expected behavior
I expected Klarna Checkout to work even if that checkbox was missing. I can't swear on it, but I think it was working fine up until a few days ago.

### Actual behavior
No shipping zone is ever matched for the customers postcode.

### Steps to reproduce the behavior

I've setup a sandbox environment with only the necessary plugins and code snippets.
The active theme is a custom `storefront-child`, with the only file being `woocommerce/checkout/form-shipping.php` and with the checkbox commented out.

[Jurassic.ninja is a service from Automattic.](https://github.com/Automattic/jurassic.ninja)

```
https://spicy-marine.jurassic.ninja will be destroyed in 7 days.

WP User: demo 
Password: xUQZIUPpE1qh

SSH User: user28bb5892 
Password: xUQZIUPpE1qh

Server path: /srv/users/user28bb5892/apps/user28bb5892/public/ 
```

*Follow these steps in an incognito window.*

1. Visit https://spicy-marine.jurassic.ninja/shop/ (will be automatically deleted in 7 days)
1. Add any product to the cart
1. Visit cart (Customer does not match any shipping zone)
1. Click proceed to checkout
1. Fill in an address: (ex. Storgatan 1, 312 30 Laholm) and click Submit
1. Shipping options are not visible, like they should be
1. Refreshing the page does not help either

### Versions
Klarna Checkout for WooCommerce - Version 2.5.6
WordPress - Version 5.7.2
WooCommerce - Version 5.3.0 and 5.4.1

#### No shipping after address filled in
![image](https://user-images.githubusercontent.com/1066486/121516867-ff721c80-c9ee-11eb-9113-4959f6c37add.png)

#### The modified template code
![image](https://user-images.githubusercontent.com/1066486/121517042-30eae800-c9ef-11eb-9b52-df7b7547cda7.png)

**Comment by adevade** [comment]
Looking closer, I believe the issue is with how we load the checkout templates based on if the user is logged in or not.
The checkbox should always be available if the option to define separate shipping address is active. 

I've worked out a solution for our special case, where we always load a template with this checkbox present if Klarna Checkout is the customers gateway.

You can take a look at this when you have the time, but feel free to close it if you don't think it's a bug.
I do however still believe that this was working up until a few days ago, but I haven't tested with older versions of your plugin.

**Comment by MichaelBengtsson** [comment]
Hi @adevade

We will investigate this over the summer to make sure that there is nothing wrong here. Im not sure what could be going wrong here to be honest so i would have to test it myself before i can tell you any more.

**Comment by MichaelBengtsson** [comment]
Hi again @adevade i have just attempted to recreate this issue and i cant. Simply removing the checkbox does not cause this to happen for me at all. Due to this i will close this since i think it has more to do with your settup and not a direct bug as you said in your last comment. If you have other information for us to look at then let me know and we will reopen the issue.
