### ISSUE TITLE
If user does not reach thank you page, KCO order ID is not cleared from session

### ISSUE THREAD

**Issue by slobodan** [krokedil/klarna-checkout-for-woocommerce#4]

**Comment by slobodan** [comment]
Possible solution: when in Klarna Checkout page, before creating or updating Klarna Checkout instance check if Klarna order is checkout_incomplete. If yes, proceed, otherwise clear WC session value for KCO order ID, then create new Klarna Checkout instance.

**Comment by MichaelBengtsson** [comment]
No longer relevant with updates that have been made.
