### ISSUE TITLE
Improve support for handling extra checkout fields

### ISSUE THREAD

**Issue by NiklasHogefjord** [krokedil/klarna-checkout-for-woocommerce#41]
- [x] Add support for letting the customer select their own user name and password when creating a new account.

- [x] Make sure that fields added via the `woocommerce_checkout_fields` filter works with our extra fields handler.

- [x] See if it is possible to display more fields than just the ones added via the `woocommerce_checkout_fields` filter.

- [x] Find a solution for adding form field validation so we can handle required fields.

**Comment by MichaelBengtsson** [comment]
Closing this since its been resolved in previous updates.
