### ISSUE TITLE
Abandoned cart compatiblity

### ISSUE THREAD

**Issue by engineerized** [krokedil/klarna-checkout-for-woocommerce#415]
When started checkout is performed the abandoned cart function don't pick the email from Klarna Checkout email field when using Klaviyo plugin, as stated before you guys have added this feature in the Klarna plugin for Mailchimp.

Should not the function work as same for Klaviyo? The Klaviyo is looking for "woocommerce_after_checkout_form" function and the Klarna Checkout plugin has that. Hopefully there is a fix our some work around to add in functions.php file.

**Comment by a-larsson** [comment]
As we do not get the email address from Klarna in this early stage it’s not possible I'm afraid.

**Comment by engineerized** [comment]
Thank you for your reply @a-larsson. I meant abandoned checkout not abandoned cart. In the checkout there is a email field that could be used with some tweaks hopefully :)

**Comment by NiklasHogefjord** [comment]
@engineerized the Klarna checkout fields are hosted (in an iframe) by Klarna. There is no way to fetch them via a hook or a filter sadly.

**Comment by engineerized** [comment]
Thank you @NiklasHogefjord. This was my concern as well as it is iframe. Is there a way to populate the email in the klarna iframe if the user input there email is the earlier step?

Maybe to use following custom filter;
```

add_filter( 'kco_wc_api_request_args', 'krokedil_change_billing_email' );

function krokedil_change_billing_email( $request_args ) {
	
	if ( method_exists( WC()->customer, 'billing_email' ) ) {
		$request_args['billing-email'] = WC()->customer->billing_email;
	}
	return $request_args;
}
```
