### ISSUE TITLE
Phone Number written to "Shipping" in order is not passed to Omnisend

### ISSUE THREAD

**Issue by silecotim** [krokedil/klarna-checkout-for-woocommerce#429]
### Description of the issue
When an order is placed using KCO, the customer's phone number is written to the **Shipping Phone** field instead of the _Billing Phone_ field. When using [Omnisend for WooCommerce](https://wordpress.org/plugins/omnisend-connect), phone numbers and email adresses of customers are automatically transferred to Omnisend upon checkout, but when the phone number is listed in **Shipping**, the number is not transferred. When the number is listed in **Billing**, it is transferred correctly. I have contacted Omnisend technical support, who tells me there is nothing they can do to fix this issue.

### Expected behavior
I guess I want to ask if you could update the plugin so the customer's number gets put in Billing instead of Shipping. It would save us a ton of manual work writing in all those numbers for the customers paying with KCO.

### Steps to reproduce the behavior
1. Install the Omnisend Plugin and connect to Omnisend Account.
2. Place an order using KCO
3. Observe the email, name and address getting transferred, but not the phone number.

### Klarna plugin version
2.6.2 

### WordPress version
5.8.1

### WooCommerce version
5.8.0

### Screenshots
This is an order placed using KCO where the phone number is written to shipping:
![shipping](https://user-images.githubusercontent.com/91796505/140268645-ca31d598-1800-433b-a6e3-cb41b34dbc9a.JPG)

This is an order placed using Vipps Express where the phone number is written to billing:
![billing](https://user-images.githubusercontent.com/91796505/140268643-9d145085-80dc-425f-a9ce-c781646d0500.JPG)

**Comment by montazarr** [comment]
Per WooCommerce standard, we save [the _shipping_ phone number](https://github.com/krokedil/klarna-checkout-for-woocommerce/blob/807eadbbd7168d2ba02251287b853f29e3fafbaf/classes/class-kco-gateway.php#L442) to the _shipping_ field. 

> phone numbers and email adresses of customers are automatically transferred to Omnisend upon checkout

We receive the phone number from Klarna once the purchase is completed. That means, while the purchase has not yet been finalized in the checkout, the phone number is not yet available. If Omnisend checks for the phone number at that point, they won't find it. However, it is available in the order's metafield `_shipping_phone` (see link above).

**Comment by silecotim** [comment]
I managed to fix this issue by enabling phone in the WooCommerce settings in the WordPress customizer.
