### ISSUE TITLE
WooCommerce notice printed in update_order_review

### ISSUE THREAD

**Issue by oxyc** [krokedil/klarna-checkout-for-woocommerce#433]
### Description of the issue

In the case of a Klarna API error, this plugin echos a woocommerce notice in the update_order_review AJAX callback, breaking the json response and thus the page rendering.

### Expected behavior

Even if there are errors, they should either be injected into the fragments of that `update_order_review` response, or not echoed at all.

### Actual behavior

At the moment, while the ?ajax=update_order_review request is running, [KCO tries to retrieve the order](https://github.com/krokedil/klarna-checkout-for-woocommerce/blob/master/classes/class-kco-api.php#L37-L41 
) and if the API returns an error, it immediately echos out a notice which breaks the json response the call is supposed to return.

```
<ul class="woocommerce-error" role="alert">
			<li>
					</li>
	</ul>
{"result":"success","messages":"","reload":false,"fragments":{"...."}}
```

Log:

> 11-18-2021 @ 10:16:17 - {"id":"....","type":"POST","title":"KCO get order","request":{"headers":{"Authorization":"Basic .....==","Content-Type":"application\/json"},"user-agent":"WordPress\/5.8; https:\/\/solarplexius.ddev.site - WooCommerce: 5.8.0 - KCO:2.6.3 - PHP Version: 8.0.7 - Krokedil","method":"GET","timeout":10},"response":{"body":null,"code":404},"timestamp":"2021-11-18 10:16:17","stack":["get_stack","format_log","request","get_klarna_order","kco_update_wc_shipping","update_shipping_method","apply_filters00000000032231e0000000001592a705update_shipping_method : 1","do_action00000000032231e0000000001592a705update_shipping_method : 1","do_action","calculate_totals","update_order_review","apply_filtersWC_Cache_Helper::update_geolocation_hash : 10","do_actionWC_Cache_Helper::update_geolocation_hash : 10","do_action","do_wc_ajax","apply_filters_wp_admin_bar_init : 0","do_action_wp_admin_bar_init : 0","do_action","require_once","require"],"plugin_version":"2.6.3"}

### Steps to reproduce the behavior

Fake an error from the get order call while the checkout page is loading.

### Klarna plugin version

v2.6.3

### WordPress version

v5.8.2

### WooCommerce version

v5.9.0

### Screenshots

<img width="346" alt="Screen Shot 2021-11-18 at 07 40 10" src="https://user-images.githubusercontent.com/302736/142400258-1a5a0f51-ec79-4b10-839c-990b74d16aac.png">

**Comment by montazarr** [comment]
This should be fixed in the mentioned commit.
