### ISSUE TITLE
Error code: BAD VALUE when using WPML

### ISSUE THREAD

**Issue by nikolap994** [krokedil/klarna-checkout-for-woocommerce#435]
We are using WPML on the site and when we are limiting allowed countries per site klarna throws an error,
Error Code: BAD VALUE.

Here is the code to limit allowed countries:
```
/**
 * Limit shipping countries.
 *
 * @param  array $countries Countries.
 */
function sc_allowed_countries( $countries ) {
    $my_current_lang = apply_filters( 'wpml_current_language', null );

    if ( 'sv' === $my_current_lang ) {
        foreach ( $countries as $key => $value ) {
            if ( 'SE' !== $key ) {
                unset( $countries[ $key ] );
            }
        }
    } elseif ( 'en' === $my_current_lang ) {
        foreach ( $countries as $key => $value ) {
            if ( 'SE' === $key ) {
                unset( $countries[ $key ] );
            }
        }
    }

    return $countries;
}

add_filter( 'woocommerce_countries_allowed_countries', 'sc_allowed_countries', 10, 1 );
```

When switching languages from EN to SV it should automatically pick SV country and currency code but it fails throwing the following error.
<img width="1709" alt="Screen Shot 2021-11-19 at 9 30 48 AM" src="https://user-images.githubusercontent.com/25112021/144027445-44572330-bb38-4212-8c7f-0c302a9a22ef.png">

**Comment by montazarr** [comment]
The error happens because Klarna recognize (through your IP address) that your purchase country is Austria which uses Euro whereas the store's currency is set to SEK.

**Comment by nikolap994** [comment]
This is immposible, during 3 tests, 2 from Serbia and one from Sweden it always throws this error. PO country cannot be Austria if it looks by IP address.
We also tried using the VPN and same issues are reproduced. 

How come Klarna cannot handle currency changing and throw this type of error on checkout ?

**Comment by montazarr** [comment]
The error message we receive back _from Klarna_ is that the customer's identified country is Austria, whereas the store's currency is set to EURO.

You can find a list of compatible [multi-currency plugin](https://docs.krokedil.com/klarna-checkout-for-woocommerce/get-started/compatible-plugins/#multi-currency) in our documentation. One of those compatible plugins is [WPML](https://sv.wordpress.org/plugins/woocommerce-multilingual/), so it should work. I suggest you [get in touch](https://krokedil.com/contact/) with our support team. You can refer them to this Github issue.
