### ISSUE TITLE
User-Agent - add PHP version to User-Agent (for KCO, KP, & OM)

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#44]
It would be useful when debugging issues to include the PHP version in the User-Agent

**Comment by kristibarbosky** [comment]
Looks great, thanks!
  "User-Agent" : "WordPress/4.9.5; https://wp-kco.mageklarna.com - KCO:1.4.0 - PHP Version: 5.6.33 - Krokedil",
[WordPress/4.9.5; https://wp-kco.mageklarna.com - OM:1.2.3 - PHP Version: 5.6.33 - Krokedil]

**Comment by NiklasHogefjord** [comment]
Great! Closing this.
