### ISSUE TITLE
Payson-reference in KCO-templating

### ISSUE THREAD

**Issue by Dronki** [krokedil/klarna-checkout-for-woocommerce#460]
Shouldn't this line be refering to `klarna-checkout-pay.php`?
https://github.com/krokedil/klarna-checkout-for-woocommerce/blob/37b4e246b6f5f98f518c00dd34c1dd176daf120b/classes/class-kco-templates.php#L126

**Comment by montazarr** [comment]
Thank you for noticing this! We'll fix it.
