### ISSUE TITLE
Klarna checkout should not allow checkout without a shipping method

### ISSUE THREAD

**Issue by forsvunnet** [krokedil/klarna-checkout-for-woocommerce#47]
![image](https://user-images.githubusercontent.com/799281/40004973-388dc37a-5797-11e8-901c-b52b1828e034.png)

Currently you can check out and pay even if no shipping method is available.

**Comment by NiklasHogefjord** [comment]
This fix is now pushed live in https://github.com/krokedil/klarna-checkout-for-woocommerce/releases/tag/1.5.0. I'm closing this issue now but feel free to reopen it if it doesn't solve your problem.
