### ISSUE TITLE
Invalid argument for foreach

### ISSUE THREAD

**Issue by cherrycoding** [krokedil/klarna-checkout-for-woocommerce#487]
I am getting a lot of these errors in my log
`AH01071: Got error 'PHP message: PHP Warning:  Invalid argument supplied for foreach() in /var/www/vhosts/SHOP/httpdocs/wp-content/plugins/klarna-checkout-for-woocommerce/classes/class-kco-ajax.php on line 70', referer: MY URL`
Does anybody else have this problem? I dont see any error within this funtction
Thanks

**Comment by wuspum** [comment]
Im experiencing this problem too

**Comment by mntzrr** [comment]
We have not had any reports regarding this issue, so it seems like the fix fulfilled its purpose. I am closing this. Thanks for filing the issue!
