### ISSUE TITLE
Order status is pending payment

### ISSUE THREAD

**Issue by niklaswallerstedt** [krokedil/klarna-checkout-for-woocommerce#49]
Good evening, sorry if this is the wrong forum and feel free to close it. We received an order today marked as pending payment in WC. I have not seen this status for Klarna before, although for other gateways which would indicate that the user never completed checkout. Does this mean that the customer never submitted the order in KCO? No order notes or anything about the order in the EU-portal. I have looked at the docs and couldn't find anything about it.

We're running KCO 1.4.0 and Klarna Order Management 1.2.4.

**Comment by MichaelBengtsson** [comment]
Hi @niklaswallerstedt.

Could you please email us at info@krokedil.se with a wp-admin login and we can take a look at the issue.
I will close this issues for now, and we can take a look at it in the support ticket.

**Comment by niklaswallerstedt** [comment]
@MichaelBengtsson Ok, I have sent credentials and info about this ticket. I haven’t heard anything back yet.
