### ISSUE TITLE
Possibly an issue, possibly not?

### ISSUE THREAD

**Issue by Dekadinious** [krokedil/klarna-checkout-for-woocommerce#499]
### Description of the issue
Should this:

`$available_gateways = WC()->payment_gateways()->get_available_payment_gateways();`

be like this:

`$available_gateways = WC()->payment_gateways->get_available_payment_gateways();`

in all places where this code occurs?

**Comment by mntzrr** [comment]
For all intents and purposes, they're practically the same.

The only difference is that [`payment_gateways`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-woocommerce.php#L165-L169) is calling `WC()->__get('payment_gateways')` whereas [`payment_gateways()`](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-woocommerce.php#L924-L926) is calling the public method.

I hope this clarifies!
