### ISSUE TITLE
Possible typo?

### ISSUE THREAD

**Issue by Dekadinious** [krokedil/klarna-checkout-for-woocommerce#517]
Line 620 in kco-functions.php

$order->set_status( 'canceled', __( 'Klarna Checkout order was rejected', 'klarna-checkout-for-woocommerce' ) );

Should it be "cancelled"?

**Comment by mntzrr** [comment]
It should indeed be "cancelled". Thank you for notifying us about this. This has now been fixed by @bhrugesh96.
