### ISSUE TITLE
Spelling in Privacy tab

### ISSUE THREAD

**Issue by niklaswallerstedt** [krokedil/klarna-checkout-for-woocommerce#53]
Minor spelling issue (in bold) for the Privacy Policy Guide text.

> Source: Klarna Checkout for WooCommerce
When you place an order in the webstore with Klarna Checkout as the choosen payment method, information about the products in the order (**namne**, price, quantity, SKU) is sent to Klarna. When the purchase is finalized Klarna sends your billing and shipping address back to the webstore. This data plus an unique identifier for the purchase is then stored as billing and shipping data in the order in WooCommerce.

**Comment by MichaelBengtsson** [comment]
@niklaswallerstedt Thank you for pointing this out to us. This has been fixed for the next version.
