### ISSUE TITLE
Broken handling of meta queries

### ISSUE THREAD

**Issue by moory-se** [krokedil/klarna-checkout-for-woocommerce#544]
https://github.com/krokedil/klarna-checkout-for-woocommerce/compare/2.10.2...2.11.0#diff-42335c418d1d7e83d81e7c5513fe89ba53183e7037122430771db5b5a188c8a9R71 is not the correct way to handle meta queries. In practise, it's ignored meaning that $orders will be the 10 latest orders. The reset($orders) then obviously returns "the latest order" which is not very likely the on we're looking for. We're looking for one with a given meta value.

This code is used in more places than the linked one.

**Comment by MichaelBengtsson** [comment]
Thank you for reporting this. Yes this was correct, and should be resolved with version 2.11.2, with an extra check to ensure we don't process the wrong order as well.
