### ISSUE TITLE
wp_options settings not updated.

### ISSUE THREAD

**Issue by jonasostrom** [krokedil/klarna-checkout-for-woocommerce#56]
Notice: Undefined index: display_privacy_policy_text in /wp-content/plugins/klarna-checkout-for-woocommerce/includes/class-klarna-checkout-for-woocommerce-gdpr.php on line 52

Checked the json-array in the database and the display_privacy_policy_text is missing. 

Anyway to repair the wp_options for klarna-checkout-for-woocommerce?

wocommerce: 3.4.1
klarna-checkout-for-woocommerce: 1.52

**Comment by MichaelBengtsson** [comment]
@jonasostrom Hi,

Could you try to resave the settings for the Klarna plugin? That should solve the issue.

**Comment by jonasostrom** [comment]
Worked!
