### ISSUE TITLE
Compatibility with Monsterinsights

### ISSUE THREAD

**Issue by niklaswallerstedt** [krokedil/klarna-checkout-for-woocommerce#57]
We’re using Monsterinsights for Google Analytics-tracking and their ecommerce extension to feed data in to GA about purchases. We noticed recently that one of our top products were “order-received”. We contacted MI and they gave this response:

> The issue is with Klarna--we have known issues with their plugin because they don't use the default WooC hooks. We've been in touch with their developers for over a year now, but they haven't fixed it. This is not unique to us, but rather this happens to all GA integrations.

What’s your take on this? Any chance of fixing the compatibility between the plugins?

**Comment by NiklasHogefjord** [comment]
Hi Niklas,
This comment from MonsterInsights refer to https://github.com/krokedil/woocommerce-gateway-klarna. 

This plugin (the new plugin for Klarna Checkout) should not have any problem with compatibility with MonsterInsights.

**Comment by niklaswallerstedt** [comment]
Ok, we have only used the new plug-in for our site and we’re still seeing this. I’ll point MI to this issue, maybe there is something else causing this.

**Comment by NiklasHogefjord** [comment]
Do you see any other issues with the KCO plugin? Do you get any error messages in the order notes in orders?

Also, if you take a look at the KCO status section in --> WooCommerce -- > Status --> System Status. What does it say there? How many % of the orders are being created on the API callback?

![image](https://user-images.githubusercontent.com/985946/41109328-0fcf6342-6a77-11e8-8b0a-fdb61c163775.png)

**Comment by niklaswallerstedt** [comment]
@NiklasHogefjord Forgot to follow up on this one, it says 0% via callback, but we have seen two orders with the same error message recently.

`This order was made as a fallback due to an error in the checkout (Error message: An account is already registered with your email address. Please log in.). Please verify the order with Klarna.`

Almost all orders are through Klarna and we're still seeing this even for the last 7 days.
![screen shot 2018-06-18 at 22 08 23](https://user-images.githubusercontent.com/2744846/41559452-58f80238-7344-11e8-97ac-9c59eacc6fa1.png)

**Comment by NiklasHogefjord** [comment]
@niklaswallerstedt The error message means that the initial WooCommerce checkout form submission failed. The plugin then creates the order via a fallback feature. The API-callback order creation is a third (and last) option to create the order in WooCommerce. The order note are saying that there has been an existing customer making a purchase. This customer has not been logged in and in the WooCommerce settings you have configured it so that the customer should not be able to finalize a  purchase without first logging in. At the moment we can't handle this in the KCO plugin.

To avoid this error you need to uncheck the box _Display returning customer login reminder_ (WC below w 3.4) or _Allow customers to log into an existing account during checkout_ (WC 3.4+) in the Accounts settings tab.

Regarding the Monster Insights / Order received issue - we will test this in our demo store. I'll respond when we know more. (@boozebrorsan can you check this?)

**Comment by NiklasHogefjord** [comment]
@niklaswallerstedt Sorry for the delay. We will follow up on it. @boozebrorsan  - can you take a look at this and test?

**Comment by niklaswallerstedt** [comment]
Thanks, would be great to get this fixed!

**Comment by boozebrorsan** [comment]
@niklaswallerstedt 

<img width="948" alt="skarmavbild 2018-08-28 kl 12 01 16" src="https://user-images.githubusercontent.com/2573170/44716724-6f6fbc00-aabb-11e8-8372-954e8c95f969.png">

Hi,

For me it looks OK (I added a screenshot). Where do you find that "Top Products"? Can you give me a step by step instruction so I can locate it?

**Comment by niklaswallerstedt** [comment]
@boozebrorsan Very strange then... I have the latest version of MI and for the last 7 days the top product is Order received both in their dashboard and the same view as your screenshot in Analytics.

You can find the Top Products inside the dashboard of MI - Reports -> Ecommerce (in the top bar)

**Comment by boozebrorsan** [comment]
@niklaswallerstedt Can you email us instead so we can check the settings etc on the site?   Drop us an email on info@krokedil.se

**Comment by niklaswallerstedt** [comment]
Sure, will do that!

**Comment by boozebrorsan** [comment]
Hi, just following up on this question. Have you managed to solve it or is it still the same?

**Comment by niklaswallerstedt** [comment]
I haven't had the time to follow up, I'm sending an email now linking to this issue. The issue is still present.

**Comment by niklaswallerstedt** [comment]
Andreas in your support team was very helpful and tracked down the issue. There were 3 webhooks still present from an uninstalled plugin. Removing them solved the issue and the product data is now displaying. Thanks a lot!
