### ISSUE TITLE
Deprecated warnings on PHP 8.2.13

### ISSUE THREAD

**Issue by Dekadinious** [krokedil/klarna-checkout-for-woocommerce#572]
### Description of the issue
Deprecated: Creation of dynamic property KCO_Request_Create::$settings is deprecated in /www/wp-content/plugins/klarna-checkout-for-woocommerce/classes/requests/class-kco-request.php on line 30
Deprecated: Creation of dynamic property KCO_Request_Create::$shop_country is deprecated in /www/wp-content/plugins/klarna-checkout-for-woocommerce/classes/requests/class-kco-request.php on line 34
Deprecated: Creation of dynamic property KCO_Request_Options::$settings is deprecated in /www/wp-content/plugins/klarna-checkout-for-woocommerce/classes/requests/helpers/class-kco-request-options.php on line 22
Deprecated: Creation of dynamic property KCO_Request_Cart::$total_amount is deprecated in /www/wp-content/plugins/klarna-checkout-for-woocommerce/classes/requests/helpers/class-kco-request-cart.php on line 182
Deprecated: Creation of dynamic property KCO_Request_Cart::$subtotal_amount is deprecated in /www/wp-content/plugins/klarna-checkout-for-woocommerce/classes/requests/helpers/class-kco-request-cart.php on line 183
Deprecated: Creation of dynamic property KCO_Request_Cart::$total_tax_amount is deprecated in /www/wp-content/plugins/klarna-checkout-for-woocommerce/classes/requests/helpers/class-kco-request-cart.php on line 184
Deprecated: Creation of dynamic property KCO_Request_Cart::$subtotal_tax_amount is deprecated in /www/wp-content/plugins/klarna-checkout-for-woocommerce/classes/requests/helpers/class-kco-request-cart.php on line 185
Deprecated: Creation of dynamic property KCO_Request_Cart::$quantity is deprecated in /www/wp-content/plugins/klarna-checkout-for-woocommerce/classes/requests/helpers/class-kco-request-cart.php on line 186

### Expected behavior
No warnings.

### Actual behavior
Warnings.

### Steps to reproduce the behavior
Go to the checkout page with PHP 8.2

### Klarna plugin version
2.11.7

**Comment by mntzrr** [comment]
Thanks for reporting this. We'll take care of this.
