### ISSUE TITLE
Review when error "You need to enable and configure https to be able to use Klarna Checkout" is displayed

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#58]
A merchant is receiving this error, but while the shop supports both http and https, the checkout is forced to https.  KCO is working successfully for completed orders, so is this error message necessary?  Perhaps should the error not be displayed since https is forced for checkout?  (For reference, as of Woo 3.4, it seems the Force SSL setting config setting is gone, per https://docs.woocommerce.com/document/ssl-and-https/)

![image](https://user-images.githubusercontent.com/15654455/41113522-e14e2cd2-6a4f-11e8-935f-4e51b424fe7e.png)

**Comment by NiklasHogefjord** [comment]
The entire store need to have https for validation callbacks (and some other callbacks) to work. The website also need to force the site to https to avoid any 302 issues in API callbacks from Klarna to the store.
