### ISSUE TITLE
Multi currency?

### ISSUE THREAD

**Issue by cheh** [krokedil/klarna-checkout-for-woocommerce#59]
Hi, thanks for the great integration with Klarna.

Does it plugin supports a multi currency?
E.g. I installed a [Currency Switcher for WooCommerce](https://wordpress.org/plugins/currency-switcher-woocommerce/) plugin and get error when try to created order in NOT default currency.

Error: `Bad value:  #purchase_currency`
Default currency - http://prntscr.com/juhza7
Customer currency - http://prntscr.com/juhzv4

**Comment by MichaelBengtsson** [comment]
Hi @cheh 

Yes the plugin does support multi currency. However, you need to have the currency configured for your MID. I would suggest contacting Klarna regarding this and checking if the currency is configured for you.

However, i have not tested the plugin you are using, but if it changes the currency returned by the normal WooCommerce functions it should work.
