### ISSUE TITLE
KCOv3 - various enhancements & bugs

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#6]
- [x] add warning if OM plugin is not activated when KCO plugin is activated (similar to how it works with KP)

- [x] add config option allow_separate_shipping_address - https://developers.klarna.com/api/#checkout-api__create-a-new-orderoptions__allow_separate_shipping_address

- [x] while order is in "Pending Payment" status in Woo, the Klarna order id is not listed on the order. -> the Klarna order id is listed at the top of the order, not in the order notes, e.g. "Order #115 details
Payment via Klarna Checkout (ae942d46-68a0-612a-8988-6d2937be2e4a) on November 14, 2017 @ 1:35 pm. Customer IP: 67.149.184.79"

- [x] add note for KCO orders stating "Order address should not be changed and any changes you make will not be reflected in Klarna system."

- [x] include product_url & image_url data (when available)

- [x] add config option - shipping_details  - https://developers.klarna.com/api/#checkout-api__orderoptions__shipping_details

- [x] add config option - required for all DE & AT countries cancellation_uri 
(not yet available in KCOv3 should be a few weeks, https://jira.int.klarna.net/jira/browse/KCOC-2579) - closing this for now & will reopen a separate github issue when this is available

- [x] support pending (accepted, rejected, & stopped)

- [x] need setting to newsletter signup

- [x] need setting to create customer signup

- [x] if you open a 2nd tab with KCO URL, an error is thrown "Bad value: purchase_currency".  Can this be displayed better?  This then also breaks the 1st tab if it is refreshed.  Additionally if I copy the URL to the 2nd tab while checkout is processing, the order

- [x] order_lines.type should not be in caps https://developers.klarna.com/api/#checkout-api__create-a-new-order__order_lines__type

- [x] add config option - required for all EU countries terms_uri https://developers.klarna.com/api/#checkout-api__ordermerchant_urls__terms

- [ ] provide a nice error message when Klarna credentials don't work

- [x] keep Title & Description config options & default the Title to "Klarna" for both US & EU

- [X] add field for coupon entry on checkout page

- [x] Confirmation page shouldn't list payment method as "Klarna Checkout".  Could it just say "Klarna" instead (so that we don't have to add a configuration setting for this)?

- [x] when the pending notification comes thru, don't move a cancelled order to completed status

- [x] tax is not being shown on KCO page (but is set on the order in WooC) - (this may not be recreatable now)

- [x] include config option for [mandatory DOB](https://developers.klarna.com/api/#checkout-napi__orderoptions__date_of_birth_mandatory); this should be moved outside of EU config section as it could apply to any market

- [x] support [title mandatory](https://developers.klarna.com/api/#checkout-api__orderoptions__title_mandatory) (only applies to GB)

- [x] support Gift Cards, e.g. https://docs.woocommerce.com/document/smart-coupons/

- [x] This note is not showing up for all Klarna orders "Order address should not be changed and any changes you make will not be reflected in Klarna system."

- [x] Changing shipping rates on KCO page doesn't update iframe amount when country=NL but using a US address (where there are 2 shipping rates) - closing this as it is caused by MID configuration - testing US address against NL store with these credentials works well (K501739_0e57da247fd6) for both reloading the page & switching shipping rates

- [x] support Aelia Currency Switcher, currently when checking out with a different currency (EUR) on a US store, I get a "Bad value: purchase_currency" error => the US store is not currently configured to support EUR; was correctly able to test checkout with GBP from a NL (EUR) store

- [x] add [DE prefill legal requirements](https://developers.klarna.com/en/de+php/kco-v2/prefill); this should be a configurable option; both for DE & AT

- [x] not all data is prefilled for a logged in customer (city, state, & zip were prefilled) but phone, first name, last name, & address line 1 were not prefilled

- [x] not able to edit quantity of cart items on checkout page (ajax updates) - this is working partially, but inconsistently (usually the first time I increase the quantity), when I update the quantity of cart tiem, the iframe updates as expected, but the woo page looks like it is updating but then stays as the previous quantity; the 2nd time I increase the quantity, both iframe & woo page match

- [x] User-Agent should include module name & version, currently: "User-Agent" : "WordPress/4.9; https://wp-kco.mageklarna.com"

- [x] For non-US markets, tax should be sent with the order line item, not as its own separate line item, see order e9a02abb-3adb-7fc2-adde-38b68138c29d

- [x] Passwords containing special characters (such as &) aren't working, e.g. N100062

- [x] Date of birth field should be sent as date_of_birth_mandatory (not as "dob_mandatory" ).  This date_of_birth_mandatory field must also be under options in the JSON (similar to title_mandatory & allow_separate_shipping_address): https://developers.klarna.com/api/#checkout-api__create-a-new-orderoptions__date_of_birth_mandatory

- [x] prefill all customer address fields- all customer data (including address lines, city, region, phone, etc.) should be sent to Klarna from the customer's account on the shop system, currently it seems only email, postal code, & country are sent, see correlation_id: d96c1a8b-22fe-413e-8a49-799bd488e91c

**Comment by slobodan** [comment]
"add config option - required for all EU countries terms_uri https://developers.klarna.com/api/#checkout-api__ordermerchant_urls__terms"

@kristibarbosky WooCommerce has this, under Settings > Checkout, that is what we currently use, would the option you mean be for the URL or something else?.

**Comment by slobodan** [comment]
"order_lines.type should not be in caps https://developers.klarna.com/api/#checkout-api__create-a-new-order__order_lines__type" 

It's not, or I'm missing something. Where did you see it in caps?

**Comment by slobodan** [comment]
"if you open a 2nd tab with KCO URL, an error is thrown "Bad value: purchase_currency". Can this be displayed better? This then also breaks the 1st tab if it is refreshed. Additionally if I copy the URL to the 2nd tab while checkout is processing, the order"

Not getting this error, can you check again with latest from develop?

**Comment by slobodan** [comment]
Test shipping_details with DE

**Comment by slobodan** [comment]
Missed the fact that shipping_details needs to be part of options array when creating order.

![screen shot 2017-10-30 at 12 15 01](https://user-images.githubusercontent.com/129607/32168229-058e8146-bd6c-11e7-84ab-3e680e143626.png)

**Comment by slobodan** [comment]
Pending orders now work (same as with Klarna Payments, Order Management plugin is required to handle pending orders).

There could be a potential issue with it though.

With Klarna Checkout plugin, we do not have WooCommerce order when creating Klarna Checkout instance. That means:

1. We can't send WooCommerce order ID as parameter in notification_url, like we do with KP and
2. There's no guarantees WooCommerce order will exist when notification callback for pending order happens

The first is not a big problem, because we can find WooCommerce order based on Klarna order ID.

The second could be a problem if, at the time notification callback happens, we still do not have WooCommerce order created. 

WooCommerce order is created right after iframe is submitted, and backup order creation happens on confirmation callback (2 minutes after iframe is submitted), so if notification callback is guaranteed to not happen before confirmation callback, this is good. Otherwise a scheduling function needs to be added, that would run on notification callback and schedule an even 5 (arbitrary) minutes, which is when we would make changes to WooCommerce order based on results of Klarna pending order review outcome.

**Comment by slobodan** [comment]
Newsletter signup, and all other checkout fields that can't be populated by information returned from Klarna now work.

**Comment by slobodan** [comment]
Create new account - works the same way as standard WooCommerce flow. There's a "Create customer account checkbox, then based on how WC is configured, when you check the checkbox it will show you username and password fields.

**Comment by slobodan** [comment]
> Confirmation page shouldn't list payment method as "Klarna Checkout". Could it just say "Klarna" instead (so that we don't have to add a configuration setting for this)?

@kristibarbosky I think because of this, we should add back title and description settings. This being WooCommerce, we will run into merchants who want to customize checkout page and show title and/or description somewhere. All other gateways have those fields and they could be expected in some scenarios.

**Comment by kristibarbosky** [comment]
@slobodan - yes, please add title & description back into config settings.

**Comment by slobodan** [comment]
Added back the fields, a set for each API (EU/US).

US = base country means US title/description is used, otherwise EU ones.

**Comment by slobodan** [comment]
@kristibarbosky "This note is not showing up for all Klarna orders "Order address should not be changed and any changes you make will not be reflected in Klarna system."

This note is only shown if order billing country is *not* US. That's how it is in KP as well. Should it be all countries?

**Comment by kristibarbosky** [comment]
@slobodan - I confirmed with US merchant support that it would be best to have this note on all orders (both US & EU) now.  (overriding the previous comment from https://github.com/krokedil/klarna-payments-for-woocommerce/issues/13).  Can you please update that both for KP & KCO (but please let me know if you'd like me to create another GitHub issue to cover this request)?

**Comment by kristibarbosky** [comment]
@slobodan - for "Changing shipping rates on KCO page doesn't update iframe amount when country=NL but using a US address (where there are 2 shipping rates)", here is a screen shot where the totals in & outside the iframe don't match
![multiple shipping nl store us address](https://user-images.githubusercontent.com/15654455/33333416-c90f166a-d434-11e7-9845-fa34e0fcee93.png)

**Comment by slobodan** [comment]
@kristibarbosky added user agent to API requests, but can't confirm it works properly, can you check this?

**Comment by slobodan** [comment]
Can't edit order address message now shows regardless of country, for both KP (develop) and KCO
