### ISSUE TITLE
Feature request: PostNord compatibility.

### ISSUE THREAD

**Issue by MichaelBengtsson** [krokedil/klarna-checkout-for-woocommerce#67]
Swedishmixology wants us to look into compatibility for the official PostNord plugin for WooCommerce for Klarna Checkout for WooCommerce.

**Comment by SiKth** [comment]
Any updates for this?

**Comment by MichaelBengtsson** [comment]
Closing this for now. At the moment this compatibility is not possible.

**Comment by kristibarbosky** [comment]
Leaving this ticket closed, but for reference, PostNord could be supported within Klarna Checkout if the merchant uses the Klarna Shipping Service, see: https://developers.klarna.com/documentation/merchant-shipping/ & https://docs.krokedil.com/article/298-klarna-shipping-service-for-woocommerce
