### ISSUE TITLE
After multiple attempts to use PayPal from KCO, "The following fields are required: terms." error appears

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#74]
When progressing through KCO and selecting the payment method PayPal from within the iframe the error "The following fields are required: terms." was received when clicking 'Proceed to PayPal' even though the Terms and Conditions were agreed to.

![image](https://user-images.githubusercontent.com/15654455/43470312-4912df26-94b6-11e8-8d06-73249a440ee5.png)

 

In order to re-create go to any Woo KCO merchant (e.g. test site - https://wp-kco.mageklarna.com/product/joes-cat-shirt/)

 

Access KCO, select PayPal, check the agree to T+Cs box and click Proceed to PayPal..
Once redirected to PayPal click return to store.
Load the checkout again. Select PayPal, agree to T+Cs and then Proceed to PayPal.
You will then be presented with the error.

 

https://www.useloom.com/share/508259ce212d41029c82bad415946804 (When I tried this time it took two cancels to reproduce)

**Comment by kristibarbosky** [comment]
(Sorry - I should have created this under the https://github.com/krokedil/klarna-checkout-external-payment-method-for-woocommerce repo.  Let me know if you want me to close this ticket and create a new ticket there.)

**Comment by NiklasHogefjord** [comment]
No problem @kristibarbosky, we can keep it here.

I'll look into this.

**Comment by NiklasHogefjord** [comment]
I've looked into this and I can't recreate the issue in my test store. I think that this commit - 23379bda547eef9c9f2ed362b61389da5b7f6022 - included in the latest version (v1.5.5) solved this.

Can you double check in your store @kristibarbosky ?

**Comment by kristibarbosky** [comment]
This is also working well for me now testing with the latest version 1.5.5.  I'll ask the merchant to retest as well.  Thanks!

**Comment by MichaelBengtsson** [comment]
Closing since there seems to be a fix for this that is working. Reopen if that is not the case.
