### ISSUE TITLE
Send larger image to Klarna than thumbnail size

### ISSUE THREAD

**Issue by NiklasHogefjord** [krokedil/klarna-checkout-for-woocommerce#75]
https://github.com/krokedil/klarna-checkout-for-woocommerce/blob/master/includes/class-klarna-checkout-for-woocommerce-order-lines.php#L440.

What size would be optimal?

**Comment by kristibarbosky** [comment]
https://developers.klarna.com/api/#checkout-api__create-a-new-order__order_lines__image_url doesn't specify a size, but I think Klarna will resize the image, if needed.  Can you send the default/main product image displayed on the Woo product page?

**Comment by NiklasHogefjord** [comment]
Thanks @kristibarbosky.

fixed in 6f65dcc863b692b1eeba9e446f563c200e3f7acb now.

**Comment by NiklasHogefjord** [comment]
Included in the 1.5.5 release - https://github.com/krokedil/klarna-checkout-for-woocommerce/releases/tag/1.5.5
