### ISSUE TITLE
Avoid creation of double orders in Woo

### ISSUE THREAD

**Issue by NiklasHogefjord** [krokedil/klarna-checkout-for-woocommerce#77]
This can happen in some edge cases when something goes wrong during checkout.

**Comment by NiklasHogefjord** [comment]
Hopefully fixed in b98a09fadb26285cce2cf3b9db45fb78260ac1a8.

Included in the 1.5.5 release - https://github.com/krokedil/klarna-checkout-for-woocommerce/releases/tag/1.5.5

We need to monitor this. Leaving it open for now.

**Comment by NiklasHogefjord** [comment]
Also added this fc8dc4d47e11a5a009e967db2577f06924d59865 to avoid checkout form from being posted twice.

**Comment by ellinokon** [comment]
Experiencing this issue right now. Already repported it to support@krokodil.com, but thought I should mention it here as well.

An order is consistently created on submit of cart. Except for [this note](https://github.com/krokedil/klarna-checkout-for-woocommerce/blob/14ce75aec6d0402a0304a5513d20dac3a9883bf7/includes/class-klarna-checkout-for-woocommerce-gateway.php#L400) being added to the order, it is usually never again updated by Klarna via the API. Sometimes it appears that Klarna API gets confused and will hook a newer order onto this stray one. Rarely will this stray order get connected to the proper order ID in Klarna Portal.

The first order is also void of any customer details.

The second order appears to be created by the Klarna API, and is always synchronised to Klarna Portal. As far as I know this is how orders using Klarna Checkout should be created in Woocommerce: After Klarna Portal has got its data updated and under control.

The Klarna Checkout iframe consistently appears on the thank-you-page, but with a notice that the cart is empty.

I'll provide more details if necessary, though it might have to be over an email or two.

**Comment by Tobias-Conrad** [comment]
Here too, 

@NiklasHogefjord please fix

**Comment by MichaelBengtsson** [comment]
Since this seems to have been fixed at this point due to lack of support tickets with the issue the last months we are closing this issue. If this is still happening then you can reopen the issue and we will continue to investigate the issue.

**Comment by shaundraws** [comment]
Getting this bug..

**Comment by NiklasHogefjord** [comment]
@shaundraws Please get in touch directly via support@krokedil.com and we will try to assist you.
