### ISSUE TITLE
No longer log html_snippet in order meta events

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#79]
If "Log debug messages" is unchecked, when the Klarna order is accessed in the Woo admin, it tries to access this url: https://checkout-eu.playground.klarna.com/yaco/orders/{order_id}, it gets a "401 Unauthorized" error (because the order has been completed and this isn't the same customer session). 
 Because of that the error, a popup from the screenshot is triggered (infinitely until the browser is closed or go to a different page).

![image](https://user-images.githubusercontent.com/15654455/43784712-b546429c-9a32-11e8-8d5e-02d91dcf1d85.png)

To intermediately resolve the problem, the "Log debug messages" can be checked.
![image](https://user-images.githubusercontent.com/15654455/43784619-85ea98f4-9a32-11e8-86cc-23ecfdb47d56.png)

To resolve this longer term, please update code to no longer keep the KCO order confirmation html_snippet in the order meta events.

**Comment by NiklasHogefjord** [comment]
Fixed in Develop branch here - ae1bb4746264694a4fa9c86165ad0f6a0d61d8e4

**Comment by NiklasHogefjord** [comment]
Included in the 1.5.5 release - https://github.com/krokedil/klarna-checkout-for-woocommerce/releases/tag/1.5.5
