### ISSUE TITLE
Disable autofill on KCO Address field

### ISSUE THREAD

**Issue by Pautomagi** [krokedil/klarna-checkout-for-woocommerce#83]
I have this issue when entering an address without clicking the kco autofill that it wont register as a valid address.

So I have to enter part of the address, scroll down in the kco dropdown and click the address I want for it to work.

The issue is bigger when the browser autofill is turned on and some of my old addresses is the only thing i can see overlaying the kco dropdown list.

My suggestion is to turn autocomplete off for the address field in the checkout.

**Comment by MichaelBengtsson** [comment]
Hi @Pautomagi.

I believe this is an issue with Klarnas new Address Module that they implemented in the iFrame. Could you please provide us with a screenshot or a video of the issue and I can forward it to them after that.

**Comment by MichaelBengtsson** [comment]
Closing this issue due to no reply for two weeks.
