### ISSUE TITLE
Error when purchasing virtual (downloadable) products

### ISSUE THREAD

**Issue by orjansteffensen** [krokedil/klarna-checkout-for-woocommerce#84]
We have both physical products that are shipped and downloadable products that are marked in Woocommerce as virtual products. 

When customer is trying to purchase a virtual product he will get an error message stating "No shipment was selected". I can get around this by removing the "virtual" checkbox, but then shipment options are visible.

**Comment by orjansteffensen** [comment]
This is fixed now in 1.7.3. Might have been the same bug as with free trial subscriptions? 
Noticed this in changelog: 
> Fix - Fixed issue with no_shipping error on free trial subscriptions.

**Comment by samuellinde** [comment]
This seems to still be an issue. We're on 1.7.9 and see the same error.

**Comment by NiklasHogefjord** [comment]
Hi,
Sorry for the very late reply in this issue.

We got a fix in the Develop branch now that should fix this issue. We will release this in a new version within a few days but if you want to use it right away it you can just download the Develop version.
