### ISSUE TITLE
Duplicate KCO orders created (perhaps due to timeouts on push) PI-445

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#85]
A merchant is experiencing duplicate orders, but only in their live environment, not test.  
![image](https://user-images.githubusercontent.com/15654455/44587174-26003380-a780-11e8-924b-001a6eac5836.png)

They are getting timeouts on the push, see below, but can the code be updated to not create duplicate orders in this case?
message:	 Failed to post confirmation to [https://****.no/wc-api/KCO_WC_Push/?kco_wc_order_id=***] in 5131 ms: {}.	
exception:	 java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)

**Comment by NiklasHogefjord** [comment]
This is probably a case where we need to troubleshoot more in detail. Please aske them to get in touch with us  directly via support@krokedil.se.

**Comment by NiklasHogefjord** [comment]
I'm closing this issue. If the merchant was in touch with us via our support we have probably solved it.
