### ISSUE TITLE
Include WooCommerce version in User-Agent (for KP, KCO, OM)

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-checkout-for-woocommerce#86]
To enable better support, can we also get the merchant's WooCommerce version included in the User-Agent (for KP & KCO & OM) please and thank you!

**Comment by NiklasHogefjord** [comment]
Available in [version 1.9.0](https://github.com/krokedil/klarna-checkout-for-woocommerce/releases/tag/1.9.0).
