### ISSUE TITLE
Unchecking "Ship to a different address" does not seem to trigger the shipping_address_change event

### ISSUE THREAD

**Issue by NiklasHogefjord** [krokedil/klarna-checkout-for-woocommerce#92]
If I tick the checkbox _Ship to a different address_ and change the country, this triggers the _shipping_address_change_ javascript event so we update the shipping country in WooCommerce.

But unticking the same checkbox (without having filled in all the other shipping address fields) does _not_ trigger the _shipping_address_change_ event again.

Here's a video showing this:
http://g.recordit.co/fazMtPvjpf.gif

@kristibarbosky Do you think that this is something that can be improved from Klarnas side or should we handle this in another way in the plugin?

**Comment by NiklasHogefjord** [comment]
Thanks Kristi. I’ll pass this along to Andreas who’s in contact with the merchant.

**Comment by boozebrorsan** [comment]
@kristibarbosky any news on this issue?

**Comment by kristibarbosky** [comment]
@boozebrorsan - I now have the internal ticket number (KCO-899), but it is still In Progress today.   I'll update this ticket if/when I get an ETA on the fix.

**Comment by kristibarbosky** [comment]
@boozebrorsan - would this store be interested in having the new shipping module enabled for them to resolve this issue?  If so, can you provide the MID for the store?

**Comment by boozebrorsan** [comment]
@kristibarbosky do you have any more information I can give the client regarding the shipping module?

I'll ask them but I thought it might be good to send along more info :)

**Comment by TheWizl** [comment]
I am trying on every channel I can. I reported this. Now it´s even worse.

They changed the Klarna Checkout. Put the countries on top and removed another shipping-adress function.

It STILL doesnt update prices (which is different in Germany vs Sweden, VAT) AND now shipping to another adress is gone. Which is/can reduce sales.

**Comment by NiklasHogefjord** [comment]
@TheWizl Have Klarna been in direct contact with you about this? If that's the case I think it's better you keep the conversation in that conversation.

**Comment by TheWizl** [comment]
Over a month now. Really? We can´t charge customers wrong amount.

**Comment by kristibarbosky** [comment]
@TheWizl - the resolution for the shipping_change event not firing will be the new shipping module.  If you provide me your Klarna MID, I can request the new shipping module to be enabled for your MID prior to full rollout of the shipping module (per my comment 17 days ago).  Please let me know if you'd like to go that route or wait for the shipping module to be rolled out to the markets.

**Comment by TheWizl** [comment]
Ok! Whats the timeline for that roll out? And is there another way to communicate about this issue?

**Comment by kristibarbosky** [comment]
@TheWizl  - Engineering is currently testing the Shipping module with a few merchants, but they have not yet provided a timeline for roll out.  I have requested that.   If you'd prefer, you are welcome to open a Klarna merchant support case for this, since this is a Klarna issue, not a Woo/Krokedil issue.

**Comment by kristibarbosky** [comment]
@TheWizl - Wanted to give you an update that I debugged further with the engineer regarding this.  He is working on the issue and hope to have a fix for you soon (perhaps later this week).

**Comment by kristibarbosky** [comment]
@TheWizl - Klarna Checkout code has been released today with a fix for this issue.  Please review and reopen this ticket if anything further is needed.  Again, my apologies for the delay on this fix.
