### ISSUE TITLE
Mix of checkout and thank you when free order.

### ISSUE THREAD

**Issue by jonasostrom** [krokedil/klarna-checkout-for-woocommerce#94]
Hi,

I've updated to the 1.6.0 version and discovered that the commit:
`Don’t use KCO template file if cart doesn’t need payment.`
Now gives me the default checkout when it is free order but I have experienced that the klarna widget comes as "Thank you" and says that my cart is empty?

**Comment by MichaelBengtsson** [comment]
@jonasostrom I am not able to reproduce this. Do you have steps to follow to get this to trigger?

**Comment by MichaelBengtsson** [comment]
Closing this as i can't recreate this anymore using the steps above. If this is still an issue for you, feel free to reopen this issue and i will investigate it again.
